/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BadRequestResponseErrors model module.
 * @module model/BadRequestResponseErrors
 * @version 3.0.43879
 */
class BadRequestResponseErrors {
    /**
     * Constructs a new <code>BadRequestResponseErrors</code>.
     * If it was a **POST** or **PUT** request (and the **message** returned is &#x60;Validation Failed&#x60;), this field may contain **errors** that describe the errors grouped by the input parameter name. 
     * @alias module:model/BadRequestResponseErrors
     */
    constructor() { 
        
        BadRequestResponseErrors.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BadRequestResponseErrors</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BadRequestResponseErrors} obj Optional instance to populate.
     * @return {module:model/BadRequestResponseErrors} The populated <code>BadRequestResponseErrors</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BadRequestResponseErrors();

            if (data.hasOwnProperty('common')) {
                obj['common'] = ApiClient.convertToType(data['common'], ['String']);
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BadRequestResponseErrors</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BadRequestResponseErrors</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['common'])) {
            throw new Error("Expected the field `common` to be an array in the JSON data but got " + data['common']);
        }

        return true;
    }


}



/**
 * Array of messages with errors related to the entire request. For example, you did not specify either the **text** or the **templateId** when [sending the message](https://docs.textmagic.com/#tag/Outbound-Messages). 
 * @member {Array.<String>} common
 */
BadRequestResponseErrors.prototype['common'] = undefined;

/**
 * Associative array. The keys are the POST/PUT parameter names and the values are arrays with error messages for these parameters. 
 * @member {Object} fields
 */
BadRequestResponseErrors.prototype['fields'] = undefined;






export default BadRequestResponseErrors;

