/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessageSession from './MessageSession';

/**
 * The BulkSession model module.
 * @module model/BulkSession
 * @version 3.0.43879
 */
class BulkSession {
    /**
     * Constructs a new <code>BulkSession</code>.
     * @alias module:model/BulkSession
     * @param id {Number} Bulk Session ID.
     * @param status {module:model/BulkSession.StatusEnum} * **n** – bulk session is just created * **w** - work in progress * **f** - failed * **c** - completed with success * **s** - suspended 
     * @param itemsProcessed {Number} Amount of messages already processed.
     * @param itemsTotal {Number} Total amount of messages to be processed.
     * @param createdAt {Date} Creation date and time of a Bulk Session.
     * @param session {module:model/MessageSession} 
     * @param text {String} Message text of a Bulk Session.
     */
    constructor(id, status, itemsProcessed, itemsTotal, createdAt, session, text) { 
        
        BulkSession.initialize(this, id, status, itemsProcessed, itemsTotal, createdAt, session, text);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, status, itemsProcessed, itemsTotal, createdAt, session, text) { 
        obj['id'] = id;
        obj['status'] = status;
        obj['itemsProcessed'] = itemsProcessed;
        obj['itemsTotal'] = itemsTotal;
        obj['createdAt'] = createdAt;
        obj['session'] = session;
        obj['text'] = text;
    }

    /**
     * Constructs a <code>BulkSession</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BulkSession} obj Optional instance to populate.
     * @return {module:model/BulkSession} The populated <code>BulkSession</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BulkSession();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('itemsProcessed')) {
                obj['itemsProcessed'] = ApiClient.convertToType(data['itemsProcessed'], 'Number');
            }
            if (data.hasOwnProperty('itemsTotal')) {
                obj['itemsTotal'] = ApiClient.convertToType(data['itemsTotal'], 'Number');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('session')) {
                obj['session'] = MessageSession.constructFromObject(data['session']);
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BulkSession</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BulkSession</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BulkSession.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // validate the optional field `session`
        if (data['session']) { // data not null
          MessageSession.validateJSON(data['session']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }

        return true;
    }


}

BulkSession.RequiredProperties = ["id", "status", "itemsProcessed", "itemsTotal", "createdAt", "session", "text"];

/**
 * Bulk Session ID.
 * @member {Number} id
 */
BulkSession.prototype['id'] = undefined;

/**
 * * **n** – bulk session is just created * **w** - work in progress * **f** - failed * **c** - completed with success * **s** - suspended 
 * @member {module:model/BulkSession.StatusEnum} status
 */
BulkSession.prototype['status'] = undefined;

/**
 * Amount of messages already processed.
 * @member {Number} itemsProcessed
 */
BulkSession.prototype['itemsProcessed'] = undefined;

/**
 * Total amount of messages to be processed.
 * @member {Number} itemsTotal
 */
BulkSession.prototype['itemsTotal'] = undefined;

/**
 * Creation date and time of a Bulk Session.
 * @member {Date} createdAt
 */
BulkSession.prototype['createdAt'] = undefined;

/**
 * @member {module:model/MessageSession} session
 */
BulkSession.prototype['session'] = undefined;

/**
 * Message text of a Bulk Session.
 * @member {String} text
 */
BulkSession.prototype['text'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
BulkSession['StatusEnum'] = {

    /**
     * value: "n"
     * @const
     */
    "n": "n",

    /**
     * value: "w"
     * @const
     */
    "w": "w",

    /**
     * value: "f"
     * @const
     */
    "f": "f",

    /**
     * value: "c"
     * @const
     */
    "c": "c",

    /**
     * value: "s"
     * @const
     */
    "s": "s"
};



export default BulkSession;

