/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CallPriceResponse model module.
 * @module model/CallPriceResponse
 * @version 3.0.43874
 */
class CallPriceResponse {
    /**
     * Constructs a new <code>CallPriceResponse</code>.
     * @alias module:model/CallPriceResponse
     * @param outbound {Number} Price for outbound message.
     * @param inbound {Number} Price for inbound message.
     * @param forward {Number} Price for forward.
     * @param country {String} The 2-letter ISO country code for local phone numbers, used when local is  set to true. Default is account country.
     */
    constructor(outbound, inbound, forward, country) { 
        
        CallPriceResponse.initialize(this, outbound, inbound, forward, country);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, outbound, inbound, forward, country) { 
        obj['outbound'] = outbound;
        obj['inbound'] = inbound;
        obj['forward'] = forward;
        obj['country'] = country;
    }

    /**
     * Constructs a <code>CallPriceResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CallPriceResponse} obj Optional instance to populate.
     * @return {module:model/CallPriceResponse} The populated <code>CallPriceResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CallPriceResponse();

            if (data.hasOwnProperty('outbound')) {
                obj['outbound'] = ApiClient.convertToType(data['outbound'], 'Number');
            }
            if (data.hasOwnProperty('inbound')) {
                obj['inbound'] = ApiClient.convertToType(data['inbound'], 'Number');
            }
            if (data.hasOwnProperty('forward')) {
                obj['forward'] = ApiClient.convertToType(data['forward'], 'Number');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CallPriceResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CallPriceResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CallPriceResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }

        return true;
    }


}

CallPriceResponse.RequiredProperties = ["outbound", "inbound", "forward", "country"];

/**
 * Price for outbound message.
 * @member {Number} outbound
 */
CallPriceResponse.prototype['outbound'] = undefined;

/**
 * Price for inbound message.
 * @member {Number} inbound
 */
CallPriceResponse.prototype['inbound'] = undefined;

/**
 * Price for forward.
 * @member {Number} forward
 */
CallPriceResponse.prototype['forward'] = undefined;

/**
 * The 2-letter ISO country code for local phone numbers, used when local is  set to true. Default is account country.
 * @member {String} country
 */
CallPriceResponse.prototype['country'] = undefined;






export default CallPriceResponse;

