/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContactImage from './ContactImage';
import ContactNote from './ContactNote';
import Country from './Country';
import CustomFieldListItem from './CustomFieldListItem';
import Tag from './Tag';
import User from './User';

/**
 * The Contact model module.
 * @module model/Contact
 * @version 3.0.43879
 */
class Contact {
    /**
     * Constructs a new <code>Contact</code>.
     * @alias module:model/Contact
     * @param id {Number} Contact ID.
     * @param favorited {Boolean} Is the Contact favorite? [Favorite list](https://docs.textmagic.com/#operation/getFavorites).
     * @param blocked {Boolean} Is the Contact blocked? [Blocked contacts](https://docs.textmagic.com/#operation/getBlockedContacts).
     * @param firstName {String} Contact first name.
     * @param lastName {String} Contact last name.
     * @param companyName {String} Company name.
     * @param phone {String} Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).
     * @param email {String} Contact email address.
     * @param country {module:model/Country} 
     * @param customFields {Array.<module:model/CustomFieldListItem>} 
     * @param user {module:model/User} 
     * @param lists {Array.<Array>} 
     * @param phoneType {String} Phone number type: * **0** if it is fixed-line; * **1** if it is mobile; * **2** if it is mobile or fixed-line (in case we cannot distingush between fixed-line or mobile); * **3** if it is toll-free; * **4** if it is a premium rate phone; * **5** if it is a shared cost phone; * **6** if it is a VoIP; * **7** if it is a [Personal Number](); * **8** if it is a pager; * **9** if it is a Universal Access Number; * **10** if the phone type is unknown; * **-1** if the phone type is not yet processed or cannot be determined. 
     * @param avatar {module:model/ContactImage} 
     * @param notes {Array.<module:model/ContactNote>} 
     */
    constructor(id, favorited, blocked, firstName, lastName, companyName, phone, email, country, customFields, user, lists, phoneType, avatar, notes) { 
        
        Contact.initialize(this, id, favorited, blocked, firstName, lastName, companyName, phone, email, country, customFields, user, lists, phoneType, avatar, notes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, favorited, blocked, firstName, lastName, companyName, phone, email, country, customFields, user, lists, phoneType, avatar, notes) { 
        obj['id'] = id;
        obj['favorited'] = favorited;
        obj['blocked'] = blocked;
        obj['firstName'] = firstName;
        obj['lastName'] = lastName;
        obj['companyName'] = companyName;
        obj['phone'] = phone;
        obj['email'] = email;
        obj['country'] = country;
        obj['customFields'] = customFields;
        obj['user'] = user;
        obj['lists'] = lists;
        obj['phoneType'] = phoneType;
        obj['avatar'] = avatar;
        obj['notes'] = notes;
    }

    /**
     * Constructs a <code>Contact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Contact} obj Optional instance to populate.
     * @return {module:model/Contact} The populated <code>Contact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Contact();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('favorited')) {
                obj['favorited'] = ApiClient.convertToType(data['favorited'], 'Boolean');
            }
            if (data.hasOwnProperty('blocked')) {
                obj['blocked'] = ApiClient.convertToType(data['blocked'], 'Boolean');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('companyName')) {
                obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = Country.constructFromObject(data['country']);
            }
            if (data.hasOwnProperty('customFields')) {
                obj['customFields'] = ApiClient.convertToType(data['customFields'], [CustomFieldListItem]);
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('lists')) {
                obj['lists'] = ApiClient.convertToType(data['lists'], [Array]);
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = User.constructFromObject(data['owner']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [Tag]);
            }
            if (data.hasOwnProperty('phoneType')) {
                obj['phoneType'] = ApiClient.convertToType(data['phoneType'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ContactImage.constructFromObject(data['avatar']);
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], [ContactNote]);
            }
            if (data.hasOwnProperty('whatsappPhone')) {
                obj['whatsappPhone'] = ApiClient.convertToType(data['whatsappPhone'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Contact</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Contact</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Contact.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }
        // ensure the json data is a string
        if (data['companyName'] && !(typeof data['companyName'] === 'string' || data['companyName'] instanceof String)) {
            throw new Error("Expected the field `companyName` to be a primitive type in the JSON string but got " + data['companyName']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // validate the optional field `country`
        if (data['country']) { // data not null
          Country.validateJSON(data['country']);
        }
        if (data['customFields']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['customFields'])) {
                throw new Error("Expected the field `customFields` to be an array in the JSON data but got " + data['customFields']);
            }
            // validate the optional field `customFields` (array)
            for (const item of data['customFields']) {
                CustomFieldListItem.validateJSON(item);
            };
        }
        // validate the optional field `user`
        if (data['user']) { // data not null
          User.validateJSON(data['user']);
        }
        if (data['lists']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['lists'])) {
                throw new Error("Expected the field `lists` to be an array in the JSON data but got " + data['lists']);
            }
            // validate the optional field `lists` (array)
            for (const item of data['lists']) {
                Array.validateJSON(item);
            };
        }
        // validate the optional field `owner`
        if (data['owner']) { // data not null
          User.validateJSON(data['owner']);
        }
        if (data['tags']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['tags'])) {
                throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
            }
            // validate the optional field `tags` (array)
            for (const item of data['tags']) {
                Tag.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['phoneType'] && !(typeof data['phoneType'] === 'string' || data['phoneType'] instanceof String)) {
            throw new Error("Expected the field `phoneType` to be a primitive type in the JSON string but got " + data['phoneType']);
        }
        // validate the optional field `avatar`
        if (data['avatar']) { // data not null
          ContactImage.validateJSON(data['avatar']);
        }
        if (data['notes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['notes'])) {
                throw new Error("Expected the field `notes` to be an array in the JSON data but got " + data['notes']);
            }
            // validate the optional field `notes` (array)
            for (const item of data['notes']) {
                ContactNote.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['whatsappPhone'] && !(typeof data['whatsappPhone'] === 'string' || data['whatsappPhone'] instanceof String)) {
            throw new Error("Expected the field `whatsappPhone` to be a primitive type in the JSON string but got " + data['whatsappPhone']);
        }

        return true;
    }


}

Contact.RequiredProperties = ["id", "favorited", "blocked", "firstName", "lastName", "companyName", "phone", "email", "country", "customFields", "user", "lists", "phoneType", "avatar", "notes"];

/**
 * Contact ID.
 * @member {Number} id
 */
Contact.prototype['id'] = undefined;

/**
 * Is the Contact favorite? [Favorite list](https://docs.textmagic.com/#operation/getFavorites).
 * @member {Boolean} favorited
 */
Contact.prototype['favorited'] = undefined;

/**
 * Is the Contact blocked? [Blocked contacts](https://docs.textmagic.com/#operation/getBlockedContacts).
 * @member {Boolean} blocked
 */
Contact.prototype['blocked'] = undefined;

/**
 * Contact first name.
 * @member {String} firstName
 */
Contact.prototype['firstName'] = undefined;

/**
 * Contact last name.
 * @member {String} lastName
 */
Contact.prototype['lastName'] = undefined;

/**
 * Company name.
 * @member {String} companyName
 */
Contact.prototype['companyName'] = undefined;

/**
 * Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).
 * @member {String} phone
 */
Contact.prototype['phone'] = undefined;

/**
 * Contact email address.
 * @member {String} email
 */
Contact.prototype['email'] = undefined;

/**
 * @member {module:model/Country} country
 */
Contact.prototype['country'] = undefined;

/**
 * @member {Array.<module:model/CustomFieldListItem>} customFields
 */
Contact.prototype['customFields'] = undefined;

/**
 * @member {module:model/User} user
 */
Contact.prototype['user'] = undefined;

/**
 * @member {Array.<Array>} lists
 */
Contact.prototype['lists'] = undefined;

/**
 * @member {module:model/User} owner
 */
Contact.prototype['owner'] = undefined;

/**
 * @member {Array.<module:model/Tag>} tags
 */
Contact.prototype['tags'] = undefined;

/**
 * Phone number type: * **0** if it is fixed-line; * **1** if it is mobile; * **2** if it is mobile or fixed-line (in case we cannot distingush between fixed-line or mobile); * **3** if it is toll-free; * **4** if it is a premium rate phone; * **5** if it is a shared cost phone; * **6** if it is a VoIP; * **7** if it is a [Personal Number](); * **8** if it is a pager; * **9** if it is a Universal Access Number; * **10** if the phone type is unknown; * **-1** if the phone type is not yet processed or cannot be determined. 
 * @member {String} phoneType
 */
Contact.prototype['phoneType'] = undefined;

/**
 * @member {module:model/ContactImage} avatar
 */
Contact.prototype['avatar'] = undefined;

/**
 * @member {Array.<module:model/ContactNote>} notes
 */
Contact.prototype['notes'] = undefined;

/**
 * Whatsapp phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).
 * @member {String} whatsappPhone
 */
Contact.prototype['whatsappPhone'] = undefined;






export default Contact;

