/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessagePayload from './MessagePayload';

/**
 * The Conversation model module.
 * @module model/Conversation
 * @version 3.0.43874
 */
class Conversation {
    /**
     * Constructs a new <code>Conversation</code>.
     * @alias module:model/Conversation
     * @param id {Number} 
     * @param direction {module:model/Conversation.DirectionEnum} Message type: inbound or outbound. 
     * @param sender {String} Sender phone number.
     * @param messageTime {Date} Time when  the message arrived at Textmagic.
     * @param text {String} Message text.
     * @param receiver {String} Receiver's phone number.
     * @param status {String} Message status (for chats outbound only). See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details.
     * @param firstName {String} Contact first name.
     * @param lastName {String} Contact last name.
     * @param sessionId {Number} Session ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.
     */
    constructor(id, direction, sender, messageTime, text, receiver, status, firstName, lastName, sessionId) { 
        
        Conversation.initialize(this, id, direction, sender, messageTime, text, receiver, status, firstName, lastName, sessionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, direction, sender, messageTime, text, receiver, status, firstName, lastName, sessionId) { 
        obj['id'] = id;
        obj['direction'] = direction;
        obj['sender'] = sender;
        obj['messageTime'] = messageTime;
        obj['text'] = text;
        obj['receiver'] = receiver;
        obj['status'] = status;
        obj['firstName'] = firstName;
        obj['lastName'] = lastName;
        obj['sessionId'] = sessionId;
    }

    /**
     * Constructs a <code>Conversation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Conversation} obj Optional instance to populate.
     * @return {module:model/Conversation} The populated <code>Conversation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Conversation();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('direction')) {
                obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
            }
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = ApiClient.convertToType(data['sender'], 'String');
            }
            if (data.hasOwnProperty('messageTime')) {
                obj['messageTime'] = ApiClient.convertToType(data['messageTime'], 'Date');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('receiver')) {
                obj['receiver'] = ApiClient.convertToType(data['receiver'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('sessionId')) {
                obj['sessionId'] = ApiClient.convertToType(data['sessionId'], 'Number');
            }
            if (data.hasOwnProperty('initiatorId')) {
                obj['initiatorId'] = ApiClient.convertToType(data['initiatorId'], 'Number');
            }
            if (data.hasOwnProperty('messageFileId')) {
                obj['messageFileId'] = ApiClient.convertToType(data['messageFileId'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('chatType')) {
                obj['chatType'] = ApiClient.convertToType(data['chatType'], 'String');
            }
            if (data.hasOwnProperty('chatId')) {
                obj['chatId'] = ApiClient.convertToType(data['chatId'], 'Number');
            }
            if (data.hasOwnProperty('isEdited')) {
                obj['isEdited'] = ApiClient.convertToType(data['isEdited'], 'Boolean');
            }
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'String');
            }
            if (data.hasOwnProperty('files')) {
                obj['files'] = ApiClient.convertToType(data['files'], [File]);
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = MessagePayload.constructFromObject(data['payload']);
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Conversation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Conversation</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Conversation.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['direction'] && !(typeof data['direction'] === 'string' || data['direction'] instanceof String)) {
            throw new Error("Expected the field `direction` to be a primitive type in the JSON string but got " + data['direction']);
        }
        // ensure the json data is a string
        if (data['sender'] && !(typeof data['sender'] === 'string' || data['sender'] instanceof String)) {
            throw new Error("Expected the field `sender` to be a primitive type in the JSON string but got " + data['sender']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // ensure the json data is a string
        if (data['receiver'] && !(typeof data['receiver'] === 'string' || data['receiver'] instanceof String)) {
            throw new Error("Expected the field `receiver` to be a primitive type in the JSON string but got " + data['receiver']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['chatType'] && !(typeof data['chatType'] === 'string' || data['chatType'] instanceof String)) {
            throw new Error("Expected the field `chatType` to be a primitive type in the JSON string but got " + data['chatType']);
        }
        // ensure the json data is a string
        if (data['errorCode'] && !(typeof data['errorCode'] === 'string' || data['errorCode'] instanceof String)) {
            throw new Error("Expected the field `errorCode` to be a primitive type in the JSON string but got " + data['errorCode']);
        }
        if (data['files']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['files'])) {
                throw new Error("Expected the field `files` to be an array in the JSON data but got " + data['files']);
            }
            // validate the optional field `files` (array)
            for (const item of data['files']) {
                File.validateJSON(item);
            };
        }
        // validate the optional field `payload`
        if (data['payload']) { // data not null
          MessagePayload.validateJSON(data['payload']);
        }
        // ensure the json data is a string
        if (data['avatar'] && !(typeof data['avatar'] === 'string' || data['avatar'] instanceof String)) {
            throw new Error("Expected the field `avatar` to be a primitive type in the JSON string but got " + data['avatar']);
        }

        return true;
    }


}

Conversation.RequiredProperties = ["id", "direction", "sender", "messageTime", "text", "receiver", "status", "firstName", "lastName", "sessionId"];

/**
 * @member {Number} id
 */
Conversation.prototype['id'] = undefined;

/**
 * Message type: inbound or outbound. 
 * @member {module:model/Conversation.DirectionEnum} direction
 */
Conversation.prototype['direction'] = undefined;

/**
 * Sender phone number.
 * @member {String} sender
 */
Conversation.prototype['sender'] = undefined;

/**
 * Time when  the message arrived at Textmagic.
 * @member {Date} messageTime
 */
Conversation.prototype['messageTime'] = undefined;

/**
 * Message text.
 * @member {String} text
 */
Conversation.prototype['text'] = undefined;

/**
 * Receiver's phone number.
 * @member {String} receiver
 */
Conversation.prototype['receiver'] = undefined;

/**
 * Message status (for chats outbound only). See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details.
 * @member {String} status
 */
Conversation.prototype['status'] = undefined;

/**
 * Contact first name.
 * @member {String} firstName
 */
Conversation.prototype['firstName'] = undefined;

/**
 * Contact last name.
 * @member {String} lastName
 */
Conversation.prototype['lastName'] = undefined;

/**
 * Session ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.
 * @member {Number} sessionId
 */
Conversation.prototype['sessionId'] = undefined;

/**
 * Initiator ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.
 * @member {Number} initiatorId
 */
Conversation.prototype['initiatorId'] = undefined;

/**
 * Message file id.
 * @member {Number} messageFileId
 */
Conversation.prototype['messageFileId'] = undefined;

/**
 * Message type.
 * @member {module:model/Conversation.TypeEnum} type
 */
Conversation.prototype['type'] = undefined;

/**
 * Chat type.
 * @member {module:model/Conversation.ChatTypeEnum} chatType
 */
Conversation.prototype['chatType'] = undefined;

/**
 * Chat id.
 * @member {Number} chatId
 */
Conversation.prototype['chatId'] = undefined;

/**
 * @member {Boolean} isEdited
 */
Conversation.prototype['isEdited'] = undefined;

/**
 * Error code.
 * @member {String} errorCode
 */
Conversation.prototype['errorCode'] = undefined;

/**
 * @member {Array.<File>} files
 */
Conversation.prototype['files'] = undefined;

/**
 * @member {module:model/MessagePayload} payload
 */
Conversation.prototype['payload'] = undefined;

/**
 * @member {String} avatar
 */
Conversation.prototype['avatar'] = undefined;





/**
 * Allowed values for the <code>direction</code> property.
 * @enum {String}
 * @readonly
 */
Conversation['DirectionEnum'] = {

    /**
     * value: "in"
     * @const
     */
    "in": "in",

    /**
     * value: "out"
     * @const
     */
    "out": "out",

    /**
     * value: "o"
     * @const
     */
    "o": "o",

    /**
     * value: "i"
     * @const
     */
    "i": "i"
};


/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Conversation['TypeEnum'] = {

    /**
     * value: "text"
     * @const
     */
    "text": "text",

    /**
     * value: "image"
     * @const
     */
    "image": "image",

    /**
     * value: "audio"
     * @const
     */
    "audio": "audio",

    /**
     * value: "voice"
     * @const
     */
    "voice": "voice",

    /**
     * value: "document"
     * @const
     */
    "document": "document",

    /**
     * value: "video"
     * @const
     */
    "video": "video",

    /**
     * value: "log"
     * @const
     */
    "log": "log",

    /**
     * value: "initial"
     * @const
     */
    "initial": "initial",

    /**
     * value: "note"
     * @const
     */
    "note": "note"
};


/**
 * Allowed values for the <code>chatType</code> property.
 * @enum {String}
 * @readonly
 */
Conversation['ChatTypeEnum'] = {

    /**
     * value: "sms"
     * @const
     */
    "sms": "sms",

    /**
     * value: "facebook_messenger"
     * @const
     */
    "facebook_messenger": "facebook_messenger",

    /**
     * value: "instagram"
     * @const
     */
    "instagram": "instagram",

    /**
     * value: "whatsapp_business"
     * @const
     */
    "whatsapp_business": "whatsapp_business",

    /**
     * value: "live_chat"
     * @const
     */
    "live_chat": "live_chat"
};



export default Conversation;

