/*
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EmailCampaignStatisticTotals', 'model/OutboundEmailResponse', 'model/UserPersonalInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EmailCampaignStatisticTotals'), require('./OutboundEmailResponse'), require('./UserPersonalInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.TextmagicClient) {
      root.TextmagicClient = {};
    }
    root.TextmagicClient.CreateEmailCampaignResponse = factory(root.TextmagicClient.ApiClient, root.TextmagicClient.EmailCampaignStatisticTotals, root.TextmagicClient.OutboundEmailResponse, root.TextmagicClient.UserPersonalInfo);
  }
}(this, function(ApiClient, EmailCampaignStatisticTotals, OutboundEmailResponse, UserPersonalInfo) {
  'use strict';

  /**
   * The CreateEmailCampaignResponse model module.
   * @module model/CreateEmailCampaignResponse
   * @version 2.0.43753
   */

  /**
   * Constructs a new <code>CreateEmailCampaignResponse</code>.
   * @alias module:model/CreateEmailCampaignResponse
   * @class
   * @param id {Number} Unique campaign ID.
   * @param status {module:model/CreateEmailCampaignResponse.StatusEnum} Current campaign status.
   * @param startAt {Date} Campaign start timestamp.
   * @param createdBy {module:model/UserPersonalInfo} 
   * @param fromEmail {String} Sender email address.
   * @param replyToEmail {String} Reply-to email address.
   * @param subject {String} Email subject line.
   * @param html {String} HTML email content.
   * @param cost {Number} Total campaign cost.
   * @param totals {module:model/EmailCampaignStatisticTotals} 
   */
  var exports = function(id, status, startAt, createdBy, fromEmail, replyToEmail, subject, html, cost, totals) {
    this.id = id;
    this.status = status;
    this.startAt = startAt;
    this.createdBy = createdBy;
    this.fromEmail = fromEmail;
    this.replyToEmail = replyToEmail;
    this.subject = subject;
    this.html = html;
    this.cost = cost;
    this.totals = totals;
  };

  /**
   * Constructs a <code>CreateEmailCampaignResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateEmailCampaignResponse} obj Optional instance to populate.
   * @return {module:model/CreateEmailCampaignResponse} The populated <code>CreateEmailCampaignResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('emailSenderId'))
        obj.emailSenderId = ApiClient.convertToType(data['emailSenderId'], 'Number');
      if (data.hasOwnProperty('startAt'))
        obj.startAt = ApiClient.convertToType(data['startAt'], 'Date');
      if (data.hasOwnProperty('createdBy'))
        obj.createdBy = UserPersonalInfo.constructFromObject(data['createdBy']);
      if (data.hasOwnProperty('fromName'))
        obj.fromName = ApiClient.convertToType(data['fromName'], 'String');
      if (data.hasOwnProperty('fromEmail'))
        obj.fromEmail = ApiClient.convertToType(data['fromEmail'], 'String');
      if (data.hasOwnProperty('replyToEmail'))
        obj.replyToEmail = ApiClient.convertToType(data['replyToEmail'], 'String');
      if (data.hasOwnProperty('subject'))
        obj.subject = ApiClient.convertToType(data['subject'], 'String');
      if (data.hasOwnProperty('html'))
        obj.html = ApiClient.convertToType(data['html'], 'String');
      if (data.hasOwnProperty('cost'))
        obj.cost = ApiClient.convertToType(data['cost'], 'Number');
      if (data.hasOwnProperty('totals'))
        obj.totals = EmailCampaignStatisticTotals.constructFromObject(data['totals']);
      if (data.hasOwnProperty('outboundEmail'))
        obj.outboundEmail = OutboundEmailResponse.constructFromObject(data['outboundEmail']);
      if (data.hasOwnProperty('failedReason'))
        obj.failedReason = ApiClient.convertToType(data['failedReason'], 'String');
    }
    return obj;
  }

  /**
   * Unique campaign ID.
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * Current campaign status.
   * @member {module:model/CreateEmailCampaignResponse.StatusEnum} status
   */
  exports.prototype.status = undefined;

  /**
   * Email sender ID used for this campaign.
   * @member {Number} emailSenderId
   */
  exports.prototype.emailSenderId = undefined;

  /**
   * Campaign start timestamp.
   * @member {Date} startAt
   */
  exports.prototype.startAt = undefined;

  /**
   * @member {module:model/UserPersonalInfo} createdBy
   */
  exports.prototype.createdBy = undefined;

  /**
   * Sender name displayed in recipient's inbox.
   * @member {String} fromName
   */
  exports.prototype.fromName = undefined;

  /**
   * Sender email address.
   * @member {String} fromEmail
   */
  exports.prototype.fromEmail = undefined;

  /**
   * Reply-to email address.
   * @member {String} replyToEmail
   */
  exports.prototype.replyToEmail = undefined;

  /**
   * Email subject line.
   * @member {String} subject
   */
  exports.prototype.subject = undefined;

  /**
   * HTML email content.
   * @member {String} html
   */
  exports.prototype.html = undefined;

  /**
   * Total campaign cost.
   * @member {Number} cost
   */
  exports.prototype.cost = undefined;

  /**
   * @member {module:model/EmailCampaignStatisticTotals} totals
   */
  exports.prototype.totals = undefined;

  /**
   * @member {module:model/OutboundEmailResponse} outboundEmail
   */
  exports.prototype.outboundEmail = undefined;

  /**
   * Reason for campaign failure if applicable.
   * @member {module:model/CreateEmailCampaignResponse.FailedReasonEnum} failedReason
   */
  exports.prototype.failedReason = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "idle"
     * @const
     */
    idle: "idle",

    /**
     * value: "sent"
     * @const
     */
    sent: "sent",

    /**
     * value: "in_progress"
     * @const
     */
    inProgress: "in_progress",

    /**
     * value: "failed"
     * @const
     */
    failed: "failed",

    /**
     * value: "delivered"
     * @const
     */
    delivered: "delivered",

    /**
     * value: "rejected"
     * @const
     */
    rejected: "rejected",

    /**
     * value: "error"
     * @const
     */
    error: "error",

    /**
     * value: "scheduledError"
     * @const
     */
    scheduledError: "scheduledError"
  };


  /**
   * Allowed values for the <code>failedReason</code> property.
   * @enum {String}
   * @readonly
   */
  exports.FailedReasonEnum = {
    /**
     * value: "lowBalance"
     * @const
     */
    lowBalance: "lowBalance",

    /**
     * value: "noRecipients"
     * @const
     */
    noRecipients: "noRecipients",

    /**
     * value: "noEmailSender"
     * @const
     */
    noEmailSender: "noEmailSender",

    /**
     * value: "unhandled"
     * @const
     */
    unhandled: "unhandled"
  };

  return exports;

}));
