/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateTagResponse model module.
 * @module model/CreateTagResponse
 * @version 3.0.43879
 */
class CreateTagResponse {
    /**
     * Constructs a new <code>CreateTagResponse</code>.
     * @alias module:model/CreateTagResponse
     * @param id {Number} Unique tag ID.
     * @param title {String} Tag title.
     */
    constructor(id, title) { 
        
        CreateTagResponse.initialize(this, id, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, title) { 
        obj['id'] = id;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>CreateTagResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateTagResponse} obj Optional instance to populate.
     * @return {module:model/CreateTagResponse} The populated <code>CreateTagResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateTagResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateTagResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateTagResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateTagResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}

CreateTagResponse.RequiredProperties = ["id", "title"];

/**
 * Unique tag ID.
 * @member {Number} id
 */
CreateTagResponse.prototype['id'] = undefined;

/**
 * Tag title.
 * @member {String} title
 */
CreateTagResponse.prototype['title'] = undefined;






export default CreateTagResponse;

