/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EmailCampaignStatisticTotals from './EmailCampaignStatisticTotals';
import OutboundEmailResponse from './OutboundEmailResponse';
import UserPersonalInfo from './UserPersonalInfo';

/**
 * The CreateEmailCampaignResponse model module.
 * @module model/CreateEmailCampaignResponse
 * @version 3.0.43874
 */
class CreateEmailCampaignResponse {
    /**
     * Constructs a new <code>CreateEmailCampaignResponse</code>.
     * @alias module:model/CreateEmailCampaignResponse
     * @param id {Number} Unique campaign ID.
     * @param status {module:model/CreateEmailCampaignResponse.StatusEnum} Current campaign status.
     * @param startAt {Date} Campaign start timestamp.
     * @param createdBy {module:model/UserPersonalInfo} 
     * @param fromEmail {String} Sender email address.
     * @param replyToEmail {String} Reply-to email address.
     * @param subject {String} Email subject line.
     * @param html {String} HTML email content.
     * @param cost {Number} Total campaign cost.
     * @param totals {module:model/EmailCampaignStatisticTotals} 
     */
    constructor(id, status, startAt, createdBy, fromEmail, replyToEmail, subject, html, cost, totals) { 
        
        CreateEmailCampaignResponse.initialize(this, id, status, startAt, createdBy, fromEmail, replyToEmail, subject, html, cost, totals);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, status, startAt, createdBy, fromEmail, replyToEmail, subject, html, cost, totals) { 
        obj['id'] = id;
        obj['status'] = status;
        obj['startAt'] = startAt;
        obj['createdBy'] = createdBy;
        obj['fromEmail'] = fromEmail;
        obj['replyToEmail'] = replyToEmail;
        obj['subject'] = subject;
        obj['html'] = html;
        obj['cost'] = cost;
        obj['totals'] = totals;
    }

    /**
     * Constructs a <code>CreateEmailCampaignResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateEmailCampaignResponse} obj Optional instance to populate.
     * @return {module:model/CreateEmailCampaignResponse} The populated <code>CreateEmailCampaignResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateEmailCampaignResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('emailSenderId')) {
                obj['emailSenderId'] = ApiClient.convertToType(data['emailSenderId'], 'Number');
            }
            if (data.hasOwnProperty('startAt')) {
                obj['startAt'] = ApiClient.convertToType(data['startAt'], 'Date');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = UserPersonalInfo.constructFromObject(data['createdBy']);
            }
            if (data.hasOwnProperty('fromName')) {
                obj['fromName'] = ApiClient.convertToType(data['fromName'], 'String');
            }
            if (data.hasOwnProperty('fromEmail')) {
                obj['fromEmail'] = ApiClient.convertToType(data['fromEmail'], 'String');
            }
            if (data.hasOwnProperty('replyToEmail')) {
                obj['replyToEmail'] = ApiClient.convertToType(data['replyToEmail'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('html')) {
                obj['html'] = ApiClient.convertToType(data['html'], 'String');
            }
            if (data.hasOwnProperty('cost')) {
                obj['cost'] = ApiClient.convertToType(data['cost'], 'Number');
            }
            if (data.hasOwnProperty('totals')) {
                obj['totals'] = EmailCampaignStatisticTotals.constructFromObject(data['totals']);
            }
            if (data.hasOwnProperty('outboundEmail')) {
                obj['outboundEmail'] = OutboundEmailResponse.constructFromObject(data['outboundEmail']);
            }
            if (data.hasOwnProperty('failedReason')) {
                obj['failedReason'] = ApiClient.convertToType(data['failedReason'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateEmailCampaignResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateEmailCampaignResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateEmailCampaignResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // validate the optional field `createdBy`
        if (data['createdBy']) { // data not null
          UserPersonalInfo.validateJSON(data['createdBy']);
        }
        // ensure the json data is a string
        if (data['fromName'] && !(typeof data['fromName'] === 'string' || data['fromName'] instanceof String)) {
            throw new Error("Expected the field `fromName` to be a primitive type in the JSON string but got " + data['fromName']);
        }
        // ensure the json data is a string
        if (data['fromEmail'] && !(typeof data['fromEmail'] === 'string' || data['fromEmail'] instanceof String)) {
            throw new Error("Expected the field `fromEmail` to be a primitive type in the JSON string but got " + data['fromEmail']);
        }
        // ensure the json data is a string
        if (data['replyToEmail'] && !(typeof data['replyToEmail'] === 'string' || data['replyToEmail'] instanceof String)) {
            throw new Error("Expected the field `replyToEmail` to be a primitive type in the JSON string but got " + data['replyToEmail']);
        }
        // ensure the json data is a string
        if (data['subject'] && !(typeof data['subject'] === 'string' || data['subject'] instanceof String)) {
            throw new Error("Expected the field `subject` to be a primitive type in the JSON string but got " + data['subject']);
        }
        // ensure the json data is a string
        if (data['html'] && !(typeof data['html'] === 'string' || data['html'] instanceof String)) {
            throw new Error("Expected the field `html` to be a primitive type in the JSON string but got " + data['html']);
        }
        // validate the optional field `totals`
        if (data['totals']) { // data not null
          EmailCampaignStatisticTotals.validateJSON(data['totals']);
        }
        // validate the optional field `outboundEmail`
        if (data['outboundEmail']) { // data not null
          OutboundEmailResponse.validateJSON(data['outboundEmail']);
        }
        // ensure the json data is a string
        if (data['failedReason'] && !(typeof data['failedReason'] === 'string' || data['failedReason'] instanceof String)) {
            throw new Error("Expected the field `failedReason` to be a primitive type in the JSON string but got " + data['failedReason']);
        }

        return true;
    }


}

CreateEmailCampaignResponse.RequiredProperties = ["id", "status", "startAt", "createdBy", "fromEmail", "replyToEmail", "subject", "html", "cost", "totals"];

/**
 * Unique campaign ID.
 * @member {Number} id
 */
CreateEmailCampaignResponse.prototype['id'] = undefined;

/**
 * Current campaign status.
 * @member {module:model/CreateEmailCampaignResponse.StatusEnum} status
 */
CreateEmailCampaignResponse.prototype['status'] = undefined;

/**
 * Email sender ID used for this campaign.
 * @member {Number} emailSenderId
 */
CreateEmailCampaignResponse.prototype['emailSenderId'] = undefined;

/**
 * Campaign start timestamp.
 * @member {Date} startAt
 */
CreateEmailCampaignResponse.prototype['startAt'] = undefined;

/**
 * @member {module:model/UserPersonalInfo} createdBy
 */
CreateEmailCampaignResponse.prototype['createdBy'] = undefined;

/**
 * Sender name displayed in recipient's inbox.
 * @member {String} fromName
 */
CreateEmailCampaignResponse.prototype['fromName'] = undefined;

/**
 * Sender email address.
 * @member {String} fromEmail
 */
CreateEmailCampaignResponse.prototype['fromEmail'] = undefined;

/**
 * Reply-to email address.
 * @member {String} replyToEmail
 */
CreateEmailCampaignResponse.prototype['replyToEmail'] = undefined;

/**
 * Email subject line.
 * @member {String} subject
 */
CreateEmailCampaignResponse.prototype['subject'] = undefined;

/**
 * HTML email content.
 * @member {String} html
 */
CreateEmailCampaignResponse.prototype['html'] = undefined;

/**
 * Total campaign cost.
 * @member {Number} cost
 */
CreateEmailCampaignResponse.prototype['cost'] = undefined;

/**
 * @member {module:model/EmailCampaignStatisticTotals} totals
 */
CreateEmailCampaignResponse.prototype['totals'] = undefined;

/**
 * @member {module:model/OutboundEmailResponse} outboundEmail
 */
CreateEmailCampaignResponse.prototype['outboundEmail'] = undefined;

/**
 * Reason for campaign failure if applicable.
 * @member {module:model/CreateEmailCampaignResponse.FailedReasonEnum} failedReason
 */
CreateEmailCampaignResponse.prototype['failedReason'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
CreateEmailCampaignResponse['StatusEnum'] = {

    /**
     * value: "idle"
     * @const
     */
    "idle": "idle",

    /**
     * value: "sent"
     * @const
     */
    "sent": "sent",

    /**
     * value: "in_progress"
     * @const
     */
    "in_progress": "in_progress",

    /**
     * value: "failed"
     * @const
     */
    "failed": "failed",

    /**
     * value: "delivered"
     * @const
     */
    "delivered": "delivered",

    /**
     * value: "rejected"
     * @const
     */
    "rejected": "rejected",

    /**
     * value: "error"
     * @const
     */
    "error": "error",

    /**
     * value: "scheduledError"
     * @const
     */
    "scheduledError": "scheduledError"
};


/**
 * Allowed values for the <code>failedReason</code> property.
 * @enum {String}
 * @readonly
 */
CreateEmailCampaignResponse['FailedReasonEnum'] = {

    /**
     * value: "lowBalance"
     * @const
     */
    "lowBalance": "lowBalance",

    /**
     * value: "noRecipients"
     * @const
     */
    "noRecipients": "noRecipients",

    /**
     * value: "noEmailSender"
     * @const
     */
    "noEmailSender": "noEmailSender",

    /**
     * value: "unhandled"
     * @const
     */
    "unhandled": "unhandled"
};



export default CreateEmailCampaignResponse;

