/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteChatMessagesRequest model module.
 * @module model/DeleteChatMessagesRequest
 * @version 3.0.43879
 */
class DeleteChatMessagesRequest {
    /**
     * Constructs a new <code>DeleteChatMessagesRequest</code>.
     * @alias module:model/DeleteChatMessagesRequest
     */
    constructor() { 
        
        DeleteChatMessagesRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeleteChatMessagesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteChatMessagesRequest} obj Optional instance to populate.
     * @return {module:model/DeleteChatMessagesRequest} The populated <code>DeleteChatMessagesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteChatMessagesRequest();

            if (data.hasOwnProperty('inbound_ids')) {
                obj['inbound_ids'] = ApiClient.convertToType(data['inbound_ids'], 'String');
            }
            if (data.hasOwnProperty('sent_ids')) {
                obj['sent_ids'] = ApiClient.convertToType(data['sent_ids'], 'String');
            }
            if (data.hasOwnProperty('calls_ids')) {
                obj['calls_ids'] = ApiClient.convertToType(data['calls_ids'], 'String');
            }
            if (data.hasOwnProperty('all')) {
                obj['all'] = ApiClient.convertToType(data['all'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteChatMessagesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteChatMessagesRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['inbound_ids'] && !(typeof data['inbound_ids'] === 'string' || data['inbound_ids'] instanceof String)) {
            throw new Error("Expected the field `inbound_ids` to be a primitive type in the JSON string but got " + data['inbound_ids']);
        }
        // ensure the json data is a string
        if (data['sent_ids'] && !(typeof data['sent_ids'] === 'string' || data['sent_ids'] instanceof String)) {
            throw new Error("Expected the field `sent_ids` to be a primitive type in the JSON string but got " + data['sent_ids']);
        }
        // ensure the json data is a string
        if (data['calls_ids'] && !(typeof data['calls_ids'] === 'string' || data['calls_ids'] instanceof String)) {
            throw new Error("Expected the field `calls_ids` to be a primitive type in the JSON string but got " + data['calls_ids']);
        }

        return true;
    }


}



/**
 * Inbound message IDs to delete. Require when \"all\" is equal to 0 (false).
 * @member {String} inbound_ids
 */
DeleteChatMessagesRequest.prototype['inbound_ids'] = undefined;

/**
 * Sent message IDs to delete. Require when \"all\" is equal to 0 (false).
 * @member {String} sent_ids
 */
DeleteChatMessagesRequest.prototype['sent_ids'] = undefined;

/**
 * Calls IDs to delete. Require when \"all\" is equal to 0 (false).
 * @member {String} calls_ids
 */
DeleteChatMessagesRequest.prototype['calls_ids'] = undefined;

/**
 * Default is 0 (false). If set to 1, all the entities will be removed.
 * @member {Boolean} all
 */
DeleteChatMessagesRequest.prototype['all'] = undefined;






export default DeleteChatMessagesRequest;

