/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteScheduledMessagesBulkRequest model module.
 * @module model/DeleteScheduledMessagesBulkRequest
 * @version 3.0.43874
 */
class DeleteScheduledMessagesBulkRequest {
    /**
     * Constructs a new <code>DeleteScheduledMessagesBulkRequest</code>.
     * @alias module:model/DeleteScheduledMessagesBulkRequest
     */
    constructor() { 
        
        DeleteScheduledMessagesBulkRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['status'] = '';
    }

    /**
     * Constructs a <code>DeleteScheduledMessagesBulkRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteScheduledMessagesBulkRequest} obj Optional instance to populate.
     * @return {module:model/DeleteScheduledMessagesBulkRequest} The populated <code>DeleteScheduledMessagesBulkRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteScheduledMessagesBulkRequest();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], 'String');
            }
            if (data.hasOwnProperty('all')) {
                obj['all'] = ApiClient.convertToType(data['all'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteScheduledMessagesBulkRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteScheduledMessagesBulkRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ids'] && !(typeof data['ids'] === 'string' || data['ids'] instanceof String)) {
            throw new Error("Expected the field `ids` to be a primitive type in the JSON string but got " + data['ids']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * Entity ID(s), separated by comma.
 * @member {String} ids
 */
DeleteScheduledMessagesBulkRequest.prototype['ids'] = undefined;

/**
 * Default is 0 (false). If set to 1, all the entities will be removed.
 * @member {Number} all
 */
DeleteScheduledMessagesBulkRequest.prototype['all'] = undefined;

/**
 * Default is an empty string (false). If set, all entities with specified status will be affected.
 * @member {String} status
 * @default ''
 */
DeleteScheduledMessagesBulkRequest.prototype['status'] = '';






export default DeleteScheduledMessagesBulkRequest;

