/*
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TextmagicClient) {
      root.TextmagicClient = {};
    }
    root.TextmagicClient.EmailCampaignStatisticTotals = factory(root.TextmagicClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The EmailCampaignStatisticTotals model module.
   * @module model/EmailCampaignStatisticTotals
   * @version 2.0.43753
   */

  /**
   * Constructs a new <code>EmailCampaignStatisticTotals</code>.
   * @alias module:model/EmailCampaignStatisticTotals
   * @class
   * @param recipients {Number} Total number of recipients.
   * @param delivered {Number} Number of emails delivered.
   * @param rejected {Number} Number of emails rejected.
   * @param failed {Number} Number of emails failed to send.
   * @param opened {Number} Number of emails opened.
   * @param clicked {Number} Number of emails with clicks.
   * @param spamReports {Number} Number of spam reports.
   * @param unsubscribed {Number} Number of unsubscribes.
   */
  var exports = function(recipients, delivered, rejected, failed, opened, clicked, spamReports, unsubscribed) {
    this.recipients = recipients;
    this.delivered = delivered;
    this.rejected = rejected;
    this.failed = failed;
    this.opened = opened;
    this.clicked = clicked;
    this.spamReports = spamReports;
    this.unsubscribed = unsubscribed;
  };

  /**
   * Constructs a <code>EmailCampaignStatisticTotals</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EmailCampaignStatisticTotals} obj Optional instance to populate.
   * @return {module:model/EmailCampaignStatisticTotals} The populated <code>EmailCampaignStatisticTotals</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('recipients'))
        obj.recipients = ApiClient.convertToType(data['recipients'], 'Number');
      if (data.hasOwnProperty('delivered'))
        obj.delivered = ApiClient.convertToType(data['delivered'], 'Number');
      if (data.hasOwnProperty('rejected'))
        obj.rejected = ApiClient.convertToType(data['rejected'], 'Number');
      if (data.hasOwnProperty('failed'))
        obj.failed = ApiClient.convertToType(data['failed'], 'Number');
      if (data.hasOwnProperty('opened'))
        obj.opened = ApiClient.convertToType(data['opened'], 'Number');
      if (data.hasOwnProperty('clicked'))
        obj.clicked = ApiClient.convertToType(data['clicked'], 'Number');
      if (data.hasOwnProperty('spamReports'))
        obj.spamReports = ApiClient.convertToType(data['spamReports'], 'Number');
      if (data.hasOwnProperty('unsubscribed'))
        obj.unsubscribed = ApiClient.convertToType(data['unsubscribed'], 'Number');
    }
    return obj;
  }

  /**
   * Total number of recipients.
   * @member {Number} recipients
   */
  exports.prototype.recipients = undefined;

  /**
   * Number of emails delivered.
   * @member {Number} delivered
   */
  exports.prototype.delivered = undefined;

  /**
   * Number of emails rejected.
   * @member {Number} rejected
   */
  exports.prototype.rejected = undefined;

  /**
   * Number of emails failed to send.
   * @member {Number} failed
   */
  exports.prototype.failed = undefined;

  /**
   * Number of emails opened.
   * @member {Number} opened
   */
  exports.prototype.opened = undefined;

  /**
   * Number of emails with clicks.
   * @member {Number} clicked
   */
  exports.prototype.clicked = undefined;

  /**
   * Number of spam reports.
   * @member {Number} spamReports
   */
  exports.prototype.spamReports = undefined;

  /**
   * Number of unsubscribes.
   * @member {Number} unsubscribed
   */
  exports.prototype.unsubscribed = undefined;

  return exports;

}));
