/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EmailCampaignStatisticTotals model module.
 * @module model/EmailCampaignStatisticTotals
 * @version 3.0.43879
 */
class EmailCampaignStatisticTotals {
    /**
     * Constructs a new <code>EmailCampaignStatisticTotals</code>.
     * @alias module:model/EmailCampaignStatisticTotals
     * @param recipients {Number} Total number of recipients.
     * @param delivered {Number} Number of emails delivered.
     * @param rejected {Number} Number of emails rejected.
     * @param failed {Number} Number of emails failed to send.
     * @param opened {Number} Number of emails opened.
     * @param clicked {Number} Number of emails with clicks.
     * @param spamReports {Number} Number of spam reports.
     * @param unsubscribed {Number} Number of unsubscribes.
     */
    constructor(recipients, delivered, rejected, failed, opened, clicked, spamReports, unsubscribed) { 
        
        EmailCampaignStatisticTotals.initialize(this, recipients, delivered, rejected, failed, opened, clicked, spamReports, unsubscribed);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, recipients, delivered, rejected, failed, opened, clicked, spamReports, unsubscribed) { 
        obj['recipients'] = recipients;
        obj['delivered'] = delivered;
        obj['rejected'] = rejected;
        obj['failed'] = failed;
        obj['opened'] = opened;
        obj['clicked'] = clicked;
        obj['spamReports'] = spamReports;
        obj['unsubscribed'] = unsubscribed;
    }

    /**
     * Constructs a <code>EmailCampaignStatisticTotals</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmailCampaignStatisticTotals} obj Optional instance to populate.
     * @return {module:model/EmailCampaignStatisticTotals} The populated <code>EmailCampaignStatisticTotals</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmailCampaignStatisticTotals();

            if (data.hasOwnProperty('recipients')) {
                obj['recipients'] = ApiClient.convertToType(data['recipients'], 'Number');
            }
            if (data.hasOwnProperty('delivered')) {
                obj['delivered'] = ApiClient.convertToType(data['delivered'], 'Number');
            }
            if (data.hasOwnProperty('rejected')) {
                obj['rejected'] = ApiClient.convertToType(data['rejected'], 'Number');
            }
            if (data.hasOwnProperty('failed')) {
                obj['failed'] = ApiClient.convertToType(data['failed'], 'Number');
            }
            if (data.hasOwnProperty('opened')) {
                obj['opened'] = ApiClient.convertToType(data['opened'], 'Number');
            }
            if (data.hasOwnProperty('clicked')) {
                obj['clicked'] = ApiClient.convertToType(data['clicked'], 'Number');
            }
            if (data.hasOwnProperty('spamReports')) {
                obj['spamReports'] = ApiClient.convertToType(data['spamReports'], 'Number');
            }
            if (data.hasOwnProperty('unsubscribed')) {
                obj['unsubscribed'] = ApiClient.convertToType(data['unsubscribed'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EmailCampaignStatisticTotals</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EmailCampaignStatisticTotals</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EmailCampaignStatisticTotals.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

EmailCampaignStatisticTotals.RequiredProperties = ["recipients", "delivered", "rejected", "failed", "opened", "clicked", "spamReports", "unsubscribed"];

/**
 * Total number of recipients.
 * @member {Number} recipients
 */
EmailCampaignStatisticTotals.prototype['recipients'] = undefined;

/**
 * Number of emails delivered.
 * @member {Number} delivered
 */
EmailCampaignStatisticTotals.prototype['delivered'] = undefined;

/**
 * Number of emails rejected.
 * @member {Number} rejected
 */
EmailCampaignStatisticTotals.prototype['rejected'] = undefined;

/**
 * Number of emails failed to send.
 * @member {Number} failed
 */
EmailCampaignStatisticTotals.prototype['failed'] = undefined;

/**
 * Number of emails opened.
 * @member {Number} opened
 */
EmailCampaignStatisticTotals.prototype['opened'] = undefined;

/**
 * Number of emails with clicks.
 * @member {Number} clicked
 */
EmailCampaignStatisticTotals.prototype['clicked'] = undefined;

/**
 * Number of spam reports.
 * @member {Number} spamReports
 */
EmailCampaignStatisticTotals.prototype['spamReports'] = undefined;

/**
 * Number of unsubscribes.
 * @member {Number} unsubscribed
 */
EmailCampaignStatisticTotals.prototype['unsubscribed'] = undefined;






export default EmailCampaignStatisticTotals;

