/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FileMetadataPreview model module.
 * @module model/FileMetadataPreview
 * @version 3.0.43874
 */
class FileMetadataPreview {
    /**
     * Constructs a new <code>FileMetadataPreview</code>.
     * @alias module:model/FileMetadataPreview
     * @param height {Number} 
     * @param width {Number} 
     */
    constructor(height, width) { 
        
        FileMetadataPreview.initialize(this, height, width);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, height, width) { 
        obj['height'] = height;
        obj['width'] = width;
    }

    /**
     * Constructs a <code>FileMetadataPreview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FileMetadataPreview} obj Optional instance to populate.
     * @return {module:model/FileMetadataPreview} The populated <code>FileMetadataPreview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileMetadataPreview();

            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FileMetadataPreview</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FileMetadataPreview</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FileMetadataPreview.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

FileMetadataPreview.RequiredProperties = ["height", "width"];

/**
 * @member {Number} height
 */
FileMetadataPreview.prototype['height'] = undefined;

/**
 * @member {Number} width
 */
FileMetadataPreview.prototype['width'] = undefined;






export default FileMetadataPreview;

