/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetAvailableSenderSettingOptionsResponse model module.
 * @module model/GetAvailableSenderSettingOptionsResponse
 * @version 3.0.43874
 */
class GetAvailableSenderSettingOptionsResponse {
    /**
     * Constructs a new <code>GetAvailableSenderSettingOptionsResponse</code>.
     * @alias module:model/GetAvailableSenderSettingOptionsResponse
     * @param dedicated {Array.<String>} Array of dedicated number strings.
     * @param user {Array.<String>} Array of verified account phone numbers (currently only one).
     * @param shared {Array.<String>} Array of shared number strings.
     * @param senderIds {Array.<String>} Array of alphanumeric sender IDs.
     * @param userCarrierTwilio {Array.<String>} Array of alphanumeric sender IDs.
     * @param userCarrierVonage {Array.<String>} Array of alphanumeric sender IDs.
     * @param userCarrierSinch {Array.<String>} Array of alphanumeric sender IDs.
     */
    constructor(dedicated, user, shared, senderIds, userCarrierTwilio, userCarrierVonage, userCarrierSinch) { 
        
        GetAvailableSenderSettingOptionsResponse.initialize(this, dedicated, user, shared, senderIds, userCarrierTwilio, userCarrierVonage, userCarrierSinch);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, dedicated, user, shared, senderIds, userCarrierTwilio, userCarrierVonage, userCarrierSinch) { 
        obj['dedicated'] = dedicated;
        obj['user'] = user;
        obj['shared'] = shared;
        obj['senderIds'] = senderIds;
        obj['userCarrierTwilio'] = userCarrierTwilio;
        obj['userCarrierVonage'] = userCarrierVonage;
        obj['userCarrierSinch'] = userCarrierSinch;
    }

    /**
     * Constructs a <code>GetAvailableSenderSettingOptionsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAvailableSenderSettingOptionsResponse} obj Optional instance to populate.
     * @return {module:model/GetAvailableSenderSettingOptionsResponse} The populated <code>GetAvailableSenderSettingOptionsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAvailableSenderSettingOptionsResponse();

            if (data.hasOwnProperty('dedicated')) {
                obj['dedicated'] = ApiClient.convertToType(data['dedicated'], ['String']);
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], ['String']);
            }
            if (data.hasOwnProperty('shared')) {
                obj['shared'] = ApiClient.convertToType(data['shared'], ['String']);
            }
            if (data.hasOwnProperty('senderIds')) {
                obj['senderIds'] = ApiClient.convertToType(data['senderIds'], ['String']);
            }
            if (data.hasOwnProperty('userCarrierTwilio')) {
                obj['userCarrierTwilio'] = ApiClient.convertToType(data['userCarrierTwilio'], ['String']);
            }
            if (data.hasOwnProperty('userCarrierVonage')) {
                obj['userCarrierVonage'] = ApiClient.convertToType(data['userCarrierVonage'], ['String']);
            }
            if (data.hasOwnProperty('userCarrierSinch')) {
                obj['userCarrierSinch'] = ApiClient.convertToType(data['userCarrierSinch'], ['String']);
            }
            if (data.hasOwnProperty('uCarrierBandwidth')) {
                obj['uCarrierBandwidth'] = ApiClient.convertToType(data['uCarrierBandwidth'], ['String']);
            }
            if (data.hasOwnProperty('ucTwilioSenderId')) {
                obj['ucTwilioSenderId'] = ApiClient.convertToType(data['ucTwilioSenderId'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetAvailableSenderSettingOptionsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetAvailableSenderSettingOptionsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetAvailableSenderSettingOptionsResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['dedicated'])) {
            throw new Error("Expected the field `dedicated` to be an array in the JSON data but got " + data['dedicated']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['user'])) {
            throw new Error("Expected the field `user` to be an array in the JSON data but got " + data['user']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['shared'])) {
            throw new Error("Expected the field `shared` to be an array in the JSON data but got " + data['shared']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['senderIds'])) {
            throw new Error("Expected the field `senderIds` to be an array in the JSON data but got " + data['senderIds']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['userCarrierTwilio'])) {
            throw new Error("Expected the field `userCarrierTwilio` to be an array in the JSON data but got " + data['userCarrierTwilio']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['userCarrierVonage'])) {
            throw new Error("Expected the field `userCarrierVonage` to be an array in the JSON data but got " + data['userCarrierVonage']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['userCarrierSinch'])) {
            throw new Error("Expected the field `userCarrierSinch` to be an array in the JSON data but got " + data['userCarrierSinch']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['uCarrierBandwidth'])) {
            throw new Error("Expected the field `uCarrierBandwidth` to be an array in the JSON data but got " + data['uCarrierBandwidth']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['ucTwilioSenderId'])) {
            throw new Error("Expected the field `ucTwilioSenderId` to be an array in the JSON data but got " + data['ucTwilioSenderId']);
        }

        return true;
    }


}

GetAvailableSenderSettingOptionsResponse.RequiredProperties = ["dedicated", "user", "shared", "senderIds", "userCarrierTwilio", "userCarrierVonage", "userCarrierSinch"];

/**
 * Array of dedicated number strings.
 * @member {Array.<String>} dedicated
 */
GetAvailableSenderSettingOptionsResponse.prototype['dedicated'] = undefined;

/**
 * Array of verified account phone numbers (currently only one).
 * @member {Array.<String>} user
 */
GetAvailableSenderSettingOptionsResponse.prototype['user'] = undefined;

/**
 * Array of shared number strings.
 * @member {Array.<String>} shared
 */
GetAvailableSenderSettingOptionsResponse.prototype['shared'] = undefined;

/**
 * Array of alphanumeric sender IDs.
 * @member {Array.<String>} senderIds
 */
GetAvailableSenderSettingOptionsResponse.prototype['senderIds'] = undefined;

/**
 * Array of alphanumeric sender IDs.
 * @member {Array.<String>} userCarrierTwilio
 */
GetAvailableSenderSettingOptionsResponse.prototype['userCarrierTwilio'] = undefined;

/**
 * Array of alphanumeric sender IDs.
 * @member {Array.<String>} userCarrierVonage
 */
GetAvailableSenderSettingOptionsResponse.prototype['userCarrierVonage'] = undefined;

/**
 * Array of alphanumeric sender IDs.
 * @member {Array.<String>} userCarrierSinch
 */
GetAvailableSenderSettingOptionsResponse.prototype['userCarrierSinch'] = undefined;

/**
 * Array of alphanumeric sender IDs.
 * @member {Array.<String>} uCarrierBandwidth
 */
GetAvailableSenderSettingOptionsResponse.prototype['uCarrierBandwidth'] = undefined;

/**
 * Array of alphanumeric sender IDs.
 * @member {Array.<String>} ucTwilioSenderId
 */
GetAvailableSenderSettingOptionsResponse.prototype['ucTwilioSenderId'] = undefined;






export default GetAvailableSenderSettingOptionsResponse;

