/*
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EmailSenderItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EmailSenderItem'));
  } else {
    // Browser globals (root is window)
    if (!root.TextmagicClient) {
      root.TextmagicClient = {};
    }
    root.TextmagicClient.GetEmailSendersResponse = factory(root.TextmagicClient.ApiClient, root.TextmagicClient.EmailSenderItem);
  }
}(this, function(ApiClient, EmailSenderItem) {
  'use strict';

  /**
   * The GetEmailSendersResponse model module.
   * @module model/GetEmailSendersResponse
   * @version 2.0.43753
   */

  /**
   * Constructs a new <code>GetEmailSendersResponse</code>.
   * @alias module:model/GetEmailSendersResponse
   * @class
   * @param items {Array.<module:model/EmailSenderItem>} Array of email sender objects.
   */
  var exports = function(items) {
    this.items = items;
  };

  /**
   * Constructs a <code>GetEmailSendersResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEmailSendersResponse} obj Optional instance to populate.
   * @return {module:model/GetEmailSendersResponse} The populated <code>GetEmailSendersResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [EmailSenderItem]);
    }
    return obj;
  }

  /**
   * Array of email sender objects.
   * @member {Array.<module:model/EmailSenderItem>} items
   */
  exports.prototype.items = undefined;

  return exports;

}));
