/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EmailSenderItem from './EmailSenderItem';

/**
 * The GetEmailSendersResponse model module.
 * @module model/GetEmailSendersResponse
 * @version 3.0.43874
 */
class GetEmailSendersResponse {
    /**
     * Constructs a new <code>GetEmailSendersResponse</code>.
     * @alias module:model/GetEmailSendersResponse
     * @param items {Array.<module:model/EmailSenderItem>} Array of email sender objects.
     */
    constructor(items) { 
        
        GetEmailSendersResponse.initialize(this, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items) { 
        obj['items'] = items;
    }

    /**
     * Constructs a <code>GetEmailSendersResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetEmailSendersResponse} obj Optional instance to populate.
     * @return {module:model/GetEmailSendersResponse} The populated <code>GetEmailSendersResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetEmailSendersResponse();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [EmailSenderItem]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetEmailSendersResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetEmailSendersResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetEmailSendersResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                EmailSenderItem.validateJSON(item);
            };
        }

        return true;
    }


}

GetEmailSendersResponse.RequiredProperties = ["items"];

/**
 * Array of email sender objects.
 * @member {Array.<module:model/EmailSenderItem>} items
 */
GetEmailSendersResponse.prototype['items'] = undefined;






export default GetEmailSendersResponse;

