/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetInboundMessagesNotificationSettingsResponse model module.
 * @module model/GetInboundMessagesNotificationSettingsResponse
 * @version 3.0.43879
 */
class GetInboundMessagesNotificationSettingsResponse {
    /**
     * Constructs a new <code>GetInboundMessagesNotificationSettingsResponse</code>.
     * @alias module:model/GetInboundMessagesNotificationSettingsResponse
     * @param inboundMessageNotification {Boolean} Should user receive notification about new incoming messages.
     * @param forwardedCallNotification {Boolean} Should user receive notification about new forwarded calls.
     * @param includeSmsHistory {Boolean} Include SMS history into notification Email.
     * @param sendInHtmlFormat {Boolean} Send Email notification in HTML format.
     * @param alertEmail1 {String} New message notification email 1.
     * @param alertEmail2 {String} New message notification email 2.
     * @param alertEmail3 {String} New message notification email 3.
     */
    constructor(inboundMessageNotification, forwardedCallNotification, includeSmsHistory, sendInHtmlFormat, alertEmail1, alertEmail2, alertEmail3) { 
        
        GetInboundMessagesNotificationSettingsResponse.initialize(this, inboundMessageNotification, forwardedCallNotification, includeSmsHistory, sendInHtmlFormat, alertEmail1, alertEmail2, alertEmail3);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, inboundMessageNotification, forwardedCallNotification, includeSmsHistory, sendInHtmlFormat, alertEmail1, alertEmail2, alertEmail3) { 
        obj['inboundMessageNotification'] = inboundMessageNotification;
        obj['forwardedCallNotification'] = forwardedCallNotification;
        obj['includeSmsHistory'] = includeSmsHistory;
        obj['sendInHtmlFormat'] = sendInHtmlFormat;
        obj['alertEmail1'] = alertEmail1;
        obj['alertEmail2'] = alertEmail2;
        obj['alertEmail3'] = alertEmail3;
    }

    /**
     * Constructs a <code>GetInboundMessagesNotificationSettingsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetInboundMessagesNotificationSettingsResponse} obj Optional instance to populate.
     * @return {module:model/GetInboundMessagesNotificationSettingsResponse} The populated <code>GetInboundMessagesNotificationSettingsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetInboundMessagesNotificationSettingsResponse();

            if (data.hasOwnProperty('inboundMessageNotification')) {
                obj['inboundMessageNotification'] = ApiClient.convertToType(data['inboundMessageNotification'], 'Boolean');
            }
            if (data.hasOwnProperty('forwardedCallNotification')) {
                obj['forwardedCallNotification'] = ApiClient.convertToType(data['forwardedCallNotification'], 'Boolean');
            }
            if (data.hasOwnProperty('includeSmsHistory')) {
                obj['includeSmsHistory'] = ApiClient.convertToType(data['includeSmsHistory'], 'Boolean');
            }
            if (data.hasOwnProperty('sendInHtmlFormat')) {
                obj['sendInHtmlFormat'] = ApiClient.convertToType(data['sendInHtmlFormat'], 'Boolean');
            }
            if (data.hasOwnProperty('alertEmail1')) {
                obj['alertEmail1'] = ApiClient.convertToType(data['alertEmail1'], 'String');
            }
            if (data.hasOwnProperty('alertEmail2')) {
                obj['alertEmail2'] = ApiClient.convertToType(data['alertEmail2'], 'String');
            }
            if (data.hasOwnProperty('alertEmail3')) {
                obj['alertEmail3'] = ApiClient.convertToType(data['alertEmail3'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetInboundMessagesNotificationSettingsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetInboundMessagesNotificationSettingsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetInboundMessagesNotificationSettingsResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['alertEmail1'] && !(typeof data['alertEmail1'] === 'string' || data['alertEmail1'] instanceof String)) {
            throw new Error("Expected the field `alertEmail1` to be a primitive type in the JSON string but got " + data['alertEmail1']);
        }
        // ensure the json data is a string
        if (data['alertEmail2'] && !(typeof data['alertEmail2'] === 'string' || data['alertEmail2'] instanceof String)) {
            throw new Error("Expected the field `alertEmail2` to be a primitive type in the JSON string but got " + data['alertEmail2']);
        }
        // ensure the json data is a string
        if (data['alertEmail3'] && !(typeof data['alertEmail3'] === 'string' || data['alertEmail3'] instanceof String)) {
            throw new Error("Expected the field `alertEmail3` to be a primitive type in the JSON string but got " + data['alertEmail3']);
        }

        return true;
    }


}

GetInboundMessagesNotificationSettingsResponse.RequiredProperties = ["inboundMessageNotification", "forwardedCallNotification", "includeSmsHistory", "sendInHtmlFormat", "alertEmail1", "alertEmail2", "alertEmail3"];

/**
 * Should user receive notification about new incoming messages.
 * @member {Boolean} inboundMessageNotification
 */
GetInboundMessagesNotificationSettingsResponse.prototype['inboundMessageNotification'] = undefined;

/**
 * Should user receive notification about new forwarded calls.
 * @member {Boolean} forwardedCallNotification
 */
GetInboundMessagesNotificationSettingsResponse.prototype['forwardedCallNotification'] = undefined;

/**
 * Include SMS history into notification Email.
 * @member {Boolean} includeSmsHistory
 */
GetInboundMessagesNotificationSettingsResponse.prototype['includeSmsHistory'] = undefined;

/**
 * Send Email notification in HTML format.
 * @member {Boolean} sendInHtmlFormat
 */
GetInboundMessagesNotificationSettingsResponse.prototype['sendInHtmlFormat'] = undefined;

/**
 * New message notification email 1.
 * @member {String} alertEmail1
 */
GetInboundMessagesNotificationSettingsResponse.prototype['alertEmail1'] = undefined;

/**
 * New message notification email 2.
 * @member {String} alertEmail2
 */
GetInboundMessagesNotificationSettingsResponse.prototype['alertEmail2'] = undefined;

/**
 * New message notification email 3.
 * @member {String} alertEmail3
 */
GetInboundMessagesNotificationSettingsResponse.prototype['alertEmail3'] = undefined;






export default GetInboundMessagesNotificationSettingsResponse;

