/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetListsOfContactPaginatedResponse model module.
 * @module model/GetListsOfContactPaginatedResponse
 * @version 3.0.43879
 */
class GetListsOfContactPaginatedResponse {
    /**
     * Constructs a new <code>GetListsOfContactPaginatedResponse</code>.
     * @alias module:model/GetListsOfContactPaginatedResponse
     * @param page {Number} 
     * @param pageCount {Number} The total number of pages.
     * @param limit {Number} The number of results per page.
     * @param resources {Array.<Array>} 
     */
    constructor(page, pageCount, limit, resources) { 
        
        GetListsOfContactPaginatedResponse.initialize(this, page, pageCount, limit, resources);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, page, pageCount, limit, resources) { 
        obj['page'] = page;
        obj['pageCount'] = pageCount;
        obj['limit'] = limit;
        obj['resources'] = resources;
    }

    /**
     * Constructs a <code>GetListsOfContactPaginatedResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetListsOfContactPaginatedResponse} obj Optional instance to populate.
     * @return {module:model/GetListsOfContactPaginatedResponse} The populated <code>GetListsOfContactPaginatedResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetListsOfContactPaginatedResponse();

            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('pageCount')) {
                obj['pageCount'] = ApiClient.convertToType(data['pageCount'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('resources')) {
                obj['resources'] = ApiClient.convertToType(data['resources'], [Array]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetListsOfContactPaginatedResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetListsOfContactPaginatedResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetListsOfContactPaginatedResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['resources']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['resources'])) {
                throw new Error("Expected the field `resources` to be an array in the JSON data but got " + data['resources']);
            }
            // validate the optional field `resources` (array)
            for (const item of data['resources']) {
                Array.validateJSON(item);
            };
        }

        return true;
    }


}

GetListsOfContactPaginatedResponse.RequiredProperties = ["page", "pageCount", "limit", "resources"];

/**
 * @member {Number} page
 */
GetListsOfContactPaginatedResponse.prototype['page'] = undefined;

/**
 * The total number of pages.
 * @member {Number} pageCount
 */
GetListsOfContactPaginatedResponse.prototype['pageCount'] = undefined;

/**
 * The number of results per page.
 * @member {Number} limit
 */
GetListsOfContactPaginatedResponse.prototype['limit'] = undefined;

/**
 * @member {Array.<Array>} resources
 */
GetListsOfContactPaginatedResponse.prototype['resources'] = undefined;






export default GetListsOfContactPaginatedResponse;

