/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetMessagePriceResponseCountriesItem model module.
 * @module model/GetMessagePriceResponseCountriesItem
 * @version 3.0.43879
 */
class GetMessagePriceResponseCountriesItem {
    /**
     * Constructs a new <code>GetMessagePriceResponseCountriesItem</code>.
     * @alias module:model/GetMessagePriceResponseCountriesItem
     * @param country {String} The 2-letter ISO country code.
     * @param countryName {String} Country name.
     * @param allowDedicated {Boolean} Is allowed to use a dedicated number?
     * @param count {Number} Parts count to send.
     * @param max {Number} Maximum parts to send.
     * @param sum {String} Total price to send.
     * @param landline {Number} Is this a landline number?
     */
    constructor(country, countryName, allowDedicated, count, max, sum, landline) { 
        
        GetMessagePriceResponseCountriesItem.initialize(this, country, countryName, allowDedicated, count, max, sum, landline);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, country, countryName, allowDedicated, count, max, sum, landline) { 
        obj['country'] = country;
        obj['countryName'] = countryName;
        obj['allowDedicated'] = allowDedicated;
        obj['count'] = count;
        obj['max'] = max;
        obj['sum'] = sum;
        obj['landline'] = landline;
    }

    /**
     * Constructs a <code>GetMessagePriceResponseCountriesItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetMessagePriceResponseCountriesItem} obj Optional instance to populate.
     * @return {module:model/GetMessagePriceResponseCountriesItem} The populated <code>GetMessagePriceResponseCountriesItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetMessagePriceResponseCountriesItem();

            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('countryName')) {
                obj['countryName'] = ApiClient.convertToType(data['countryName'], 'String');
            }
            if (data.hasOwnProperty('allowDedicated')) {
                obj['allowDedicated'] = ApiClient.convertToType(data['allowDedicated'], 'Boolean');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('max')) {
                obj['max'] = ApiClient.convertToType(data['max'], 'Number');
            }
            if (data.hasOwnProperty('sum')) {
                obj['sum'] = ApiClient.convertToType(data['sum'], 'String');
            }
            if (data.hasOwnProperty('landline')) {
                obj['landline'] = ApiClient.convertToType(data['landline'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetMessagePriceResponseCountriesItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetMessagePriceResponseCountriesItem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetMessagePriceResponseCountriesItem.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is a string
        if (data['countryName'] && !(typeof data['countryName'] === 'string' || data['countryName'] instanceof String)) {
            throw new Error("Expected the field `countryName` to be a primitive type in the JSON string but got " + data['countryName']);
        }
        // ensure the json data is a string
        if (data['sum'] && !(typeof data['sum'] === 'string' || data['sum'] instanceof String)) {
            throw new Error("Expected the field `sum` to be a primitive type in the JSON string but got " + data['sum']);
        }

        return true;
    }


}

GetMessagePriceResponseCountriesItem.RequiredProperties = ["country", "countryName", "allowDedicated", "count", "max", "sum", "landline"];

/**
 * The 2-letter ISO country code.
 * @member {String} country
 */
GetMessagePriceResponseCountriesItem.prototype['country'] = undefined;

/**
 * Country name.
 * @member {String} countryName
 */
GetMessagePriceResponseCountriesItem.prototype['countryName'] = undefined;

/**
 * Is allowed to use a dedicated number?
 * @member {Boolean} allowDedicated
 */
GetMessagePriceResponseCountriesItem.prototype['allowDedicated'] = undefined;

/**
 * Parts count to send.
 * @member {Number} count
 */
GetMessagePriceResponseCountriesItem.prototype['count'] = undefined;

/**
 * Maximum parts to send.
 * @member {Number} max
 */
GetMessagePriceResponseCountriesItem.prototype['max'] = undefined;

/**
 * Total price to send.
 * @member {String} sum
 */
GetMessagePriceResponseCountriesItem.prototype['sum'] = undefined;

/**
 * Is this a landline number?
 * @member {Number} landline
 */
GetMessagePriceResponseCountriesItem.prototype['landline'] = undefined;






export default GetMessagePriceResponseCountriesItem;

