/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetMessagePriceResponseCountriesItem from './GetMessagePriceResponseCountriesItem';

/**
 * The GetMessagePriceResponse model module.
 * @module model/GetMessagePriceResponse
 * @version 3.0.43874
 */
class GetMessagePriceResponse {
    /**
     * Constructs a new <code>GetMessagePriceResponse</code>.
     * @alias module:model/GetMessagePriceResponse
     * @param total {Number} Total price of the message.
     * @param parts {Number} Message parts (multiples of 160 characters) count.
     * @param countries {Array.<module:model/GetMessagePriceResponseCountriesItem>} 
     */
    constructor(total, parts, countries) { 
        
        GetMessagePriceResponse.initialize(this, total, parts, countries);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, total, parts, countries) { 
        obj['total'] = total;
        obj['parts'] = parts;
        obj['countries'] = countries;
    }

    /**
     * Constructs a <code>GetMessagePriceResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetMessagePriceResponse} obj Optional instance to populate.
     * @return {module:model/GetMessagePriceResponse} The populated <code>GetMessagePriceResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetMessagePriceResponse();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('parts')) {
                obj['parts'] = ApiClient.convertToType(data['parts'], 'Number');
            }
            if (data.hasOwnProperty('countries')) {
                obj['countries'] = ApiClient.convertToType(data['countries'], [GetMessagePriceResponseCountriesItem]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetMessagePriceResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetMessagePriceResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetMessagePriceResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['countries']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['countries'])) {
                throw new Error("Expected the field `countries` to be an array in the JSON data but got " + data['countries']);
            }
            // validate the optional field `countries` (array)
            for (const item of data['countries']) {
                GetMessagePriceResponseCountriesItem.validateJSON(item);
            };
        }

        return true;
    }


}

GetMessagePriceResponse.RequiredProperties = ["total", "parts", "countries"];

/**
 * Total price of the message.
 * @member {Number} total
 */
GetMessagePriceResponse.prototype['total'] = undefined;

/**
 * Message parts (multiples of 160 characters) count.
 * @member {Number} parts
 */
GetMessagePriceResponse.prototype['parts'] = undefined;

/**
 * @member {Array.<module:model/GetMessagePriceResponseCountriesItem>} countries
 */
GetMessagePriceResponse.prototype['countries'] = undefined;






export default GetMessagePriceResponse;

