/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetSurveyNodesResponse model module.
 * @module model/GetSurveyNodesResponse
 * @version 3.0.43879
 */
class GetSurveyNodesResponse {
    /**
     * Constructs a new <code>GetSurveyNodesResponse</code>.
     * @alias module:model/GetSurveyNodesResponse
     * @param nodes {Object} 
     * @param rows {Object} 
     */
    constructor(nodes, rows) { 
        
        GetSurveyNodesResponse.initialize(this, nodes, rows);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nodes, rows) { 
        obj['nodes'] = nodes;
        obj['rows'] = rows;
    }

    /**
     * Constructs a <code>GetSurveyNodesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetSurveyNodesResponse} obj Optional instance to populate.
     * @return {module:model/GetSurveyNodesResponse} The populated <code>GetSurveyNodesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSurveyNodesResponse();

            if (data.hasOwnProperty('nodes')) {
                obj['nodes'] = ApiClient.convertToType(data['nodes'], Object);
            }
            if (data.hasOwnProperty('rows')) {
                obj['rows'] = ApiClient.convertToType(data['rows'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetSurveyNodesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetSurveyNodesResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetSurveyNodesResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

GetSurveyNodesResponse.RequiredProperties = ["nodes", "rows"];

/**
 * @member {Object} nodes
 */
GetSurveyNodesResponse.prototype['nodes'] = undefined;

/**
 * @member {Object} rows
 */
GetSurveyNodesResponse.prototype['rows'] = undefined;






export default GetSurveyNodesResponse;

