/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessageTemplate model module.
 * @module model/MessageTemplate
 * @version 3.0.43879
 */
class MessageTemplate {
    /**
     * Constructs a new <code>MessageTemplate</code>.
     * @alias module:model/MessageTemplate
     * @param id {Number} Template ID.
     * @param name {String} Template name.
     * @param content {String} Template text. May contain dynamic fields inside braces. See the [Custom fields list](https://docs.textmagic.com/#tag/Templates/Custom-fields-list-(Merge-dynamic-fields)).
     * @param lastModified {Date} Time when the template was last modified.
     */
    constructor(id, name, content, lastModified) { 
        
        MessageTemplate.initialize(this, id, name, content, lastModified);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, content, lastModified) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['content'] = content;
        obj['lastModified'] = lastModified;
    }

    /**
     * Constructs a <code>MessageTemplate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageTemplate} obj Optional instance to populate.
     * @return {module:model/MessageTemplate} The populated <code>MessageTemplate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageTemplate();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('lastModified')) {
                obj['lastModified'] = ApiClient.convertToType(data['lastModified'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MessageTemplate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MessageTemplate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MessageTemplate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }

        return true;
    }


}

MessageTemplate.RequiredProperties = ["id", "name", "content", "lastModified"];

/**
 * Template ID.
 * @member {Number} id
 */
MessageTemplate.prototype['id'] = undefined;

/**
 * Template name.
 * @member {String} name
 */
MessageTemplate.prototype['name'] = undefined;

/**
 * Template text. May contain dynamic fields inside braces. See the [Custom fields list](https://docs.textmagic.com/#tag/Templates/Custom-fields-list-(Merge-dynamic-fields)).
 * @member {String} content
 */
MessageTemplate.prototype['content'] = undefined;

/**
 * Time when the template was last modified.
 * @member {Date} lastModified
 */
MessageTemplate.prototype['lastModified'] = undefined;






export default MessageTemplate;

