/*
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TextmagicClient) {
      root.TextmagicClient = {};
    }
    root.TextmagicClient.MessagePayload = factory(root.TextmagicClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The MessagePayload model module.
   * @module model/MessagePayload
   * @version 2.0.43821
   */

  /**
   * Constructs a new <code>MessagePayload</code>.
   * @alias module:model/MessagePayload
   * @class
   * @param type {String} Payload type.
   * @param mediaPreview {String} Media preview link.
   */
  var exports = function(type, mediaPreview) {
    this.type = type;
    this.mediaPreview = mediaPreview;
  };

  /**
   * Constructs a <code>MessagePayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MessagePayload} obj Optional instance to populate.
   * @return {module:model/MessagePayload} The populated <code>MessagePayload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('mediaPreview'))
        obj.mediaPreview = ApiClient.convertToType(data['mediaPreview'], 'String');
    }
    return obj;
  }

  /**
   * Payload type.
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * Media preview link.
   * @member {String} mediaPreview
   */
  exports.prototype.mediaPreview = undefined;

  return exports;

}));
