/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessagesIcsParametersRecipients from './MessagesIcsParametersRecipients';

/**
 * The MessagesIcsParameters model module.
 * @module model/MessagesIcsParameters
 * @version 3.0.43879
 */
class MessagesIcsParameters {
    /**
     * Constructs a new <code>MessagesIcsParameters</code>.
     * @alias module:model/MessagesIcsParameters
     * @param text {String} Scheduled message text.
     * @param recipients {module:model/MessagesIcsParametersRecipients} 
     */
    constructor(text, recipients) { 
        
        MessagesIcsParameters.initialize(this, text, recipients);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, text, recipients) { 
        obj['text'] = text;
        obj['recipients'] = recipients;
    }

    /**
     * Constructs a <code>MessagesIcsParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagesIcsParameters} obj Optional instance to populate.
     * @return {module:model/MessagesIcsParameters} The populated <code>MessagesIcsParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagesIcsParameters();

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('recipients')) {
                obj['recipients'] = MessagesIcsParametersRecipients.constructFromObject(data['recipients']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MessagesIcsParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MessagesIcsParameters</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MessagesIcsParameters.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // validate the optional field `recipients`
        if (data['recipients']) { // data not null
          MessagesIcsParametersRecipients.validateJSON(data['recipients']);
        }

        return true;
    }


}

MessagesIcsParameters.RequiredProperties = ["text", "recipients"];

/**
 * Scheduled message text.
 * @member {String} text
 */
MessagesIcsParameters.prototype['text'] = undefined;

/**
 * @member {module:model/MessagesIcsParametersRecipients} recipients
 */
MessagesIcsParameters.prototype['recipients'] = undefined;






export default MessagesIcsParameters;

