/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MuteChatsBulkRequest model module.
 * @module model/MuteChatsBulkRequest
 * @version 3.0.43874
 */
class MuteChatsBulkRequest {
    /**
     * Constructs a new <code>MuteChatsBulkRequest</code>.
     * @alias module:model/MuteChatsBulkRequest
     */
    constructor() { 
        
        MuteChatsBulkRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MuteChatsBulkRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MuteChatsBulkRequest} obj Optional instance to populate.
     * @return {module:model/MuteChatsBulkRequest} The populated <code>MuteChatsBulkRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MuteChatsBulkRequest();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], 'String');
            }
            if (data.hasOwnProperty('all')) {
                obj['all'] = ApiClient.convertToType(data['all'], 'Boolean');
            }
            if (data.hasOwnProperty('for')) {
                obj['for'] = ApiClient.convertToType(data['for'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MuteChatsBulkRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MuteChatsBulkRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ids'] && !(typeof data['ids'] === 'string' || data['ids'] instanceof String)) {
            throw new Error("Expected the field `ids` to be a primitive type in the JSON string but got " + data['ids']);
        }

        return true;
    }


}



/**
 * Entity ID(s), separated by comma.
 * @member {String} ids
 */
MuteChatsBulkRequest.prototype['ids'] = undefined;

/**
 * Entity ID(s), separated by comma
 * @member {Boolean} all
 */
MuteChatsBulkRequest.prototype['all'] = undefined;

/**
 * Mute for N hours.
 * @member {Number} for
 */
MuteChatsBulkRequest.prototype['for'] = undefined;






export default MuteChatsBulkRequest;

