/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PingResponse model module.
 * @module model/PingResponse
 * @version 3.0.43874
 */
class PingResponse {
    /**
     * Constructs a new <code>PingResponse</code>.
     * @alias module:model/PingResponse
     * @param userId {Number} Current user Id.
     * @param ping {String} Pong.
     * @param utcDateTime {String} Current date and time.
     */
    constructor(userId, ping, utcDateTime) { 
        
        PingResponse.initialize(this, userId, ping, utcDateTime);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId, ping, utcDateTime) { 
        obj['userId'] = userId;
        obj['ping'] = ping;
        obj['utcDateTime'] = utcDateTime;
    }

    /**
     * Constructs a <code>PingResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PingResponse} obj Optional instance to populate.
     * @return {module:model/PingResponse} The populated <code>PingResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PingResponse();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('ping')) {
                obj['ping'] = ApiClient.convertToType(data['ping'], 'String');
            }
            if (data.hasOwnProperty('utcDateTime')) {
                obj['utcDateTime'] = ApiClient.convertToType(data['utcDateTime'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PingResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PingResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PingResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['ping'] && !(typeof data['ping'] === 'string' || data['ping'] instanceof String)) {
            throw new Error("Expected the field `ping` to be a primitive type in the JSON string but got " + data['ping']);
        }
        // ensure the json data is a string
        if (data['utcDateTime'] && !(typeof data['utcDateTime'] === 'string' || data['utcDateTime'] instanceof String)) {
            throw new Error("Expected the field `utcDateTime` to be a primitive type in the JSON string but got " + data['utcDateTime']);
        }

        return true;
    }


}

PingResponse.RequiredProperties = ["userId", "ping", "utcDateTime"];

/**
 * Current user Id.
 * @member {Number} userId
 */
PingResponse.prototype['userId'] = undefined;

/**
 * Pong.
 * @member {String} ping
 */
PingResponse.prototype['ping'] = undefined;

/**
 * Current date and time.
 * @member {String} utcDateTime
 */
PingResponse.prototype['utcDateTime'] = undefined;






export default PingResponse;

