/*
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Apiv2emailcampaignsscheduleRecipients', 'model/Apiv2emailcampaignsscheduleScheduleParams'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Apiv2emailcampaignsscheduleRecipients'), require('./Apiv2emailcampaignsscheduleScheduleParams'));
  } else {
    // Browser globals (root is window)
    if (!root.TextmagicClient) {
      root.TextmagicClient = {};
    }
    root.TextmagicClient.ScheduleEmailCampaignInputObject = factory(root.TextmagicClient.ApiClient, root.TextmagicClient.Apiv2emailcampaignsscheduleRecipients, root.TextmagicClient.Apiv2emailcampaignsscheduleScheduleParams);
  }
}(this, function(ApiClient, Apiv2emailcampaignsscheduleRecipients, Apiv2emailcampaignsscheduleScheduleParams) {
  'use strict';

  /**
   * The ScheduleEmailCampaignInputObject model module.
   * @module model/ScheduleEmailCampaignInputObject
   * @version 2.0.43821
   */

  /**
   * Constructs a new <code>ScheduleEmailCampaignInputObject</code>.
   * @alias module:model/ScheduleEmailCampaignInputObject
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ScheduleEmailCampaignInputObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScheduleEmailCampaignInputObject} obj Optional instance to populate.
   * @return {module:model/ScheduleEmailCampaignInputObject} The populated <code>ScheduleEmailCampaignInputObject</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('emailSenderId'))
        obj.emailSenderId = ApiClient.convertToType(data['emailSenderId'], 'Number');
      if (data.hasOwnProperty('subject'))
        obj.subject = ApiClient.convertToType(data['subject'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('fromName'))
        obj.fromName = ApiClient.convertToType(data['fromName'], 'String');
      if (data.hasOwnProperty('replyToEmail'))
        obj.replyToEmail = ApiClient.convertToType(data['replyToEmail'], 'String');
      if (data.hasOwnProperty('recipients'))
        obj.recipients = Apiv2emailcampaignsscheduleRecipients.constructFromObject(data['recipients']);
      if (data.hasOwnProperty('scheduleParams'))
        obj.scheduleParams = Apiv2emailcampaignsscheduleScheduleParams.constructFromObject(data['scheduleParams']);
    }
    return obj;
  }

  /**
   * Email sender ID from your configured senders.
   * @member {Number} emailSenderId
   */
  exports.prototype.emailSenderId = undefined;

  /**
   * Email subject line.
   * @member {String} subject
   */
  exports.prototype.subject = undefined;

  /**
   * HTML email content.
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * Optional custom sender name.
   * @member {String} fromName
   */
  exports.prototype.fromName = undefined;

  /**
   * Optional custom reply-to email address.
   * @member {String} replyToEmail
   */
  exports.prototype.replyToEmail = undefined;

  /**
   * @member {module:model/Apiv2emailcampaignsscheduleRecipients} recipients
   */
  exports.prototype.recipients = undefined;

  /**
   * @member {module:model/Apiv2emailcampaignsscheduleScheduleParams} scheduleParams
   */
  exports.prototype.scheduleParams = undefined;

  return exports;

}));
