/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScheduleEmailCampaignRequestRecipients from './ScheduleEmailCampaignRequestRecipients';
import ScheduleEmailCampaignRequestScheduleParams from './ScheduleEmailCampaignRequestScheduleParams';

/**
 * The ScheduleEmailCampaignRequest model module.
 * @module model/ScheduleEmailCampaignRequest
 * @version 3.0.43874
 */
class ScheduleEmailCampaignRequest {
    /**
     * Constructs a new <code>ScheduleEmailCampaignRequest</code>.
     * @alias module:model/ScheduleEmailCampaignRequest
     */
    constructor() { 
        
        ScheduleEmailCampaignRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScheduleEmailCampaignRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScheduleEmailCampaignRequest} obj Optional instance to populate.
     * @return {module:model/ScheduleEmailCampaignRequest} The populated <code>ScheduleEmailCampaignRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScheduleEmailCampaignRequest();

            if (data.hasOwnProperty('emailSenderId')) {
                obj['emailSenderId'] = ApiClient.convertToType(data['emailSenderId'], 'Number');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('fromName')) {
                obj['fromName'] = ApiClient.convertToType(data['fromName'], 'String');
            }
            if (data.hasOwnProperty('replyToEmail')) {
                obj['replyToEmail'] = ApiClient.convertToType(data['replyToEmail'], 'String');
            }
            if (data.hasOwnProperty('recipients')) {
                obj['recipients'] = ScheduleEmailCampaignRequestRecipients.constructFromObject(data['recipients']);
            }
            if (data.hasOwnProperty('scheduleParams')) {
                obj['scheduleParams'] = ScheduleEmailCampaignRequestScheduleParams.constructFromObject(data['scheduleParams']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScheduleEmailCampaignRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScheduleEmailCampaignRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['subject'] && !(typeof data['subject'] === 'string' || data['subject'] instanceof String)) {
            throw new Error("Expected the field `subject` to be a primitive type in the JSON string but got " + data['subject']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['fromName'] && !(typeof data['fromName'] === 'string' || data['fromName'] instanceof String)) {
            throw new Error("Expected the field `fromName` to be a primitive type in the JSON string but got " + data['fromName']);
        }
        // ensure the json data is a string
        if (data['replyToEmail'] && !(typeof data['replyToEmail'] === 'string' || data['replyToEmail'] instanceof String)) {
            throw new Error("Expected the field `replyToEmail` to be a primitive type in the JSON string but got " + data['replyToEmail']);
        }
        // validate the optional field `recipients`
        if (data['recipients']) { // data not null
          ScheduleEmailCampaignRequestRecipients.validateJSON(data['recipients']);
        }
        // validate the optional field `scheduleParams`
        if (data['scheduleParams']) { // data not null
          ScheduleEmailCampaignRequestScheduleParams.validateJSON(data['scheduleParams']);
        }

        return true;
    }


}



/**
 * Email sender ID from your configured senders.
 * @member {Number} emailSenderId
 */
ScheduleEmailCampaignRequest.prototype['emailSenderId'] = undefined;

/**
 * Email subject line.
 * @member {String} subject
 */
ScheduleEmailCampaignRequest.prototype['subject'] = undefined;

/**
 * HTML email content.
 * @member {String} message
 */
ScheduleEmailCampaignRequest.prototype['message'] = undefined;

/**
 * Optional custom sender name.
 * @member {String} fromName
 */
ScheduleEmailCampaignRequest.prototype['fromName'] = undefined;

/**
 * Optional custom reply-to email address.
 * @member {String} replyToEmail
 */
ScheduleEmailCampaignRequest.prototype['replyToEmail'] = undefined;

/**
 * @member {module:model/ScheduleEmailCampaignRequestRecipients} recipients
 */
ScheduleEmailCampaignRequest.prototype['recipients'] = undefined;

/**
 * @member {module:model/ScheduleEmailCampaignRequestScheduleParams} scheduleParams
 */
ScheduleEmailCampaignRequest.prototype['scheduleParams'] = undefined;






export default ScheduleEmailCampaignRequest;

