/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScheduledEmailCampaignDetails from './ScheduledEmailCampaignDetails';

/**
 * The ScheduleEmailCampaignResponse model module.
 * @module model/ScheduleEmailCampaignResponse
 * @version 3.0.43879
 */
class ScheduleEmailCampaignResponse {
    /**
     * Constructs a new <code>ScheduleEmailCampaignResponse</code>.
     * @alias module:model/ScheduleEmailCampaignResponse
     * @param campaign {module:model/ScheduledEmailCampaignDetails} 
     * @param cost {Number} Estimated cost for sending this campaign.
     */
    constructor(campaign, cost) { 
        
        ScheduleEmailCampaignResponse.initialize(this, campaign, cost);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, campaign, cost) { 
        obj['campaign'] = campaign;
        obj['cost'] = cost;
    }

    /**
     * Constructs a <code>ScheduleEmailCampaignResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScheduleEmailCampaignResponse} obj Optional instance to populate.
     * @return {module:model/ScheduleEmailCampaignResponse} The populated <code>ScheduleEmailCampaignResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScheduleEmailCampaignResponse();

            if (data.hasOwnProperty('campaign')) {
                obj['campaign'] = ScheduledEmailCampaignDetails.constructFromObject(data['campaign']);
            }
            if (data.hasOwnProperty('cost')) {
                obj['cost'] = ApiClient.convertToType(data['cost'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScheduleEmailCampaignResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScheduleEmailCampaignResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ScheduleEmailCampaignResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `campaign`
        if (data['campaign']) { // data not null
          ScheduledEmailCampaignDetails.validateJSON(data['campaign']);
        }

        return true;
    }


}

ScheduleEmailCampaignResponse.RequiredProperties = ["campaign", "cost"];

/**
 * @member {module:model/ScheduledEmailCampaignDetails} campaign
 */
ScheduleEmailCampaignResponse.prototype['campaign'] = undefined;

/**
 * Estimated cost for sending this campaign.
 * @member {Number} cost
 */
ScheduleEmailCampaignResponse.prototype['cost'] = undefined;






export default ScheduleEmailCampaignResponse;

