/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScheduleEmailCampaignRequestScheduleParams model module.
 * @module model/ScheduleEmailCampaignRequestScheduleParams
 * @version 3.0.43879
 */
class ScheduleEmailCampaignRequestScheduleParams {
    /**
     * Constructs a new <code>ScheduleEmailCampaignRequestScheduleParams</code>.
     * Scheduling configuration for the campaign.
     * @alias module:model/ScheduleEmailCampaignRequestScheduleParams
     * @param startDateTime {Date} When to start sending the campaign (ISO 8601 format).
     * @param timezone {String} Timezone for the schedule (e.g., \"America/New_York\").
     */
    constructor(startDateTime, timezone) { 
        
        ScheduleEmailCampaignRequestScheduleParams.initialize(this, startDateTime, timezone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startDateTime, timezone) { 
        obj['startDateTime'] = startDateTime;
        obj['timezone'] = timezone;
    }

    /**
     * Constructs a <code>ScheduleEmailCampaignRequestScheduleParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScheduleEmailCampaignRequestScheduleParams} obj Optional instance to populate.
     * @return {module:model/ScheduleEmailCampaignRequestScheduleParams} The populated <code>ScheduleEmailCampaignRequestScheduleParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScheduleEmailCampaignRequestScheduleParams();

            if (data.hasOwnProperty('startDateTime')) {
                obj['startDateTime'] = ApiClient.convertToType(data['startDateTime'], 'Date');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('rrule')) {
                obj['rrule'] = ApiClient.convertToType(data['rrule'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScheduleEmailCampaignRequestScheduleParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScheduleEmailCampaignRequestScheduleParams</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ScheduleEmailCampaignRequestScheduleParams.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['timezone'] && !(typeof data['timezone'] === 'string' || data['timezone'] instanceof String)) {
            throw new Error("Expected the field `timezone` to be a primitive type in the JSON string but got " + data['timezone']);
        }
        // ensure the json data is a string
        if (data['rrule'] && !(typeof data['rrule'] === 'string' || data['rrule'] instanceof String)) {
            throw new Error("Expected the field `rrule` to be a primitive type in the JSON string but got " + data['rrule']);
        }

        return true;
    }


}

ScheduleEmailCampaignRequestScheduleParams.RequiredProperties = ["startDateTime", "timezone"];

/**
 * When to start sending the campaign (ISO 8601 format).
 * @member {Date} startDateTime
 */
ScheduleEmailCampaignRequestScheduleParams.prototype['startDateTime'] = undefined;

/**
 * Timezone for the schedule (e.g., \"America/New_York\").
 * @member {String} timezone
 */
ScheduleEmailCampaignRequestScheduleParams.prototype['timezone'] = undefined;

/**
 * RFC 5545 recurrence rule for recurring campaigns.
 * @member {String} rrule
 */
ScheduleEmailCampaignRequestScheduleParams.prototype['rrule'] = undefined;






export default ScheduleEmailCampaignRequestScheduleParams;

