/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SurveyRecipient from './SurveyRecipient';
import SurveySenderCountries from './SurveySenderCountries';

/**
 * The Survey model module.
 * @module model/Survey
 * @version 3.0.43879
 */
class Survey {
    /**
     * Constructs a new <code>Survey</code>.
     * @alias module:model/Survey
     * @param id {Number} 
     * @param name {String} 
     * @param status {String} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, name, status, createdAt, updatedAt) { 
        
        Survey.initialize(this, id, name, status, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, status, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['status'] = status;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>Survey</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Survey} obj Optional instance to populate.
     * @return {module:model/Survey} The populated <code>Survey</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Survey();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('receipents')) {
                obj['receipents'] = ApiClient.convertToType(data['receipents'], [SurveyRecipient]);
            }
            if (data.hasOwnProperty('countries')) {
                obj['countries'] = ApiClient.convertToType(data['countries'], [SurveySenderCountries]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Survey</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Survey</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Survey.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        if (data['receipents']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['receipents'])) {
                throw new Error("Expected the field `receipents` to be an array in the JSON data but got " + data['receipents']);
            }
            // validate the optional field `receipents` (array)
            for (const item of data['receipents']) {
                SurveyRecipient.validateJSON(item);
            };
        }
        if (data['countries']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['countries'])) {
                throw new Error("Expected the field `countries` to be an array in the JSON data but got " + data['countries']);
            }
            // validate the optional field `countries` (array)
            for (const item of data['countries']) {
                SurveySenderCountries.validateJSON(item);
            };
        }

        return true;
    }


}

Survey.RequiredProperties = ["id", "name", "status", "createdAt", "updatedAt"];

/**
 * @member {Number} id
 */
Survey.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Survey.prototype['name'] = undefined;

/**
 * @member {String} status
 */
Survey.prototype['status'] = undefined;

/**
 * @member {Date} createdAt
 */
Survey.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
Survey.prototype['updatedAt'] = undefined;

/**
 * @member {Array.<module:model/SurveyRecipient>} receipents
 */
Survey.prototype['receipents'] = undefined;

/**
 * @member {Array.<module:model/SurveySenderCountries>} countries
 */
Survey.prototype['countries'] = undefined;






export default Survey;

