/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SurveyNode model module.
 * @module model/SurveyNode
 * @version 3.0.43879
 */
class SurveyNode {
    /**
     * Constructs a new <code>SurveyNode</code>.
     * @alias module:model/SurveyNode
     * @param id {Number} 
     * @param label {String} 
     * @param body {String} 
     * @param nodeType {String} 
     * @param isEndNode {Boolean} 
     * @param sendDelay {Number} 
     * @param startNodes {Array.<String>} 
     * @param endNodes {Array.<String>} 
     */
    constructor(id, label, body, nodeType, isEndNode, sendDelay, startNodes, endNodes) { 
        
        SurveyNode.initialize(this, id, label, body, nodeType, isEndNode, sendDelay, startNodes, endNodes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, label, body, nodeType, isEndNode, sendDelay, startNodes, endNodes) { 
        obj['id'] = id;
        obj['label'] = label;
        obj['body'] = body;
        obj['nodeType'] = nodeType;
        obj['isEndNode'] = isEndNode;
        obj['sendDelay'] = sendDelay;
        obj['startNodes'] = startNodes;
        obj['endNodes'] = endNodes;
    }

    /**
     * Constructs a <code>SurveyNode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SurveyNode} obj Optional instance to populate.
     * @return {module:model/SurveyNode} The populated <code>SurveyNode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SurveyNode();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
            if (data.hasOwnProperty('nodeType')) {
                obj['nodeType'] = ApiClient.convertToType(data['nodeType'], 'String');
            }
            if (data.hasOwnProperty('isEndNode')) {
                obj['isEndNode'] = ApiClient.convertToType(data['isEndNode'], 'Boolean');
            }
            if (data.hasOwnProperty('sendDelay')) {
                obj['sendDelay'] = ApiClient.convertToType(data['sendDelay'], 'Number');
            }
            if (data.hasOwnProperty('startNodes')) {
                obj['startNodes'] = ApiClient.convertToType(data['startNodes'], ['String']);
            }
            if (data.hasOwnProperty('endNodes')) {
                obj['endNodes'] = ApiClient.convertToType(data['endNodes'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SurveyNode</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SurveyNode</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SurveyNode.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }
        // ensure the json data is a string
        if (data['body'] && !(typeof data['body'] === 'string' || data['body'] instanceof String)) {
            throw new Error("Expected the field `body` to be a primitive type in the JSON string but got " + data['body']);
        }
        // ensure the json data is a string
        if (data['nodeType'] && !(typeof data['nodeType'] === 'string' || data['nodeType'] instanceof String)) {
            throw new Error("Expected the field `nodeType` to be a primitive type in the JSON string but got " + data['nodeType']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['startNodes'])) {
            throw new Error("Expected the field `startNodes` to be an array in the JSON data but got " + data['startNodes']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['endNodes'])) {
            throw new Error("Expected the field `endNodes` to be an array in the JSON data but got " + data['endNodes']);
        }

        return true;
    }


}

SurveyNode.RequiredProperties = ["id", "label", "body", "nodeType", "isEndNode", "sendDelay", "startNodes", "endNodes"];

/**
 * @member {Number} id
 */
SurveyNode.prototype['id'] = undefined;

/**
 * @member {String} label
 */
SurveyNode.prototype['label'] = undefined;

/**
 * @member {String} body
 */
SurveyNode.prototype['body'] = undefined;

/**
 * @member {String} nodeType
 */
SurveyNode.prototype['nodeType'] = undefined;

/**
 * @member {Boolean} isEndNode
 */
SurveyNode.prototype['isEndNode'] = undefined;

/**
 * @member {Number} sendDelay
 */
SurveyNode.prototype['sendDelay'] = undefined;

/**
 * @member {Array.<String>} startNodes
 */
SurveyNode.prototype['startNodes'] = undefined;

/**
 * @member {Array.<String>} endNodes
 */
SurveyNode.prototype['endNodes'] = undefined;






export default SurveyNode;

