/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UnsubscribeContactRequest model module.
 * @module model/UnsubscribeContactRequest
 * @version 3.0.43879
 */
class UnsubscribeContactRequest {
    /**
     * Constructs a new <code>UnsubscribeContactRequest</code>.
     * @alias module:model/UnsubscribeContactRequest
     */
    constructor() { 
        
        UnsubscribeContactRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UnsubscribeContactRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UnsubscribeContactRequest} obj Optional instance to populate.
     * @return {module:model/UnsubscribeContactRequest} The populated <code>UnsubscribeContactRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UnsubscribeContactRequest();

            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('blockIncoming')) {
                obj['blockIncoming'] = ApiClient.convertToType(data['blockIncoming'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UnsubscribeContactRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UnsubscribeContactRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }

        return true;
    }


}



/**
 * Contact phone number.
 * @member {String} phone
 */
UnsubscribeContactRequest.prototype['phone'] = undefined;

/**
 * If set to 1, incoming messages from this number will be blocked.
 * @member {Number} blockIncoming
 */
UnsubscribeContactRequest.prototype['blockIncoming'] = undefined;






export default UnsubscribeContactRequest;

