/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UnsubscribedContact model module.
 * @module model/UnsubscribedContact
 * @version 3.0.43879
 */
class UnsubscribedContact {
    /**
     * Constructs a new <code>UnsubscribedContact</code>.
     * @alias module:model/UnsubscribedContact
     * @param id {Number} Unsubscribed contact ID.
     * @param phone {String} Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).
     * @param unsubscribeTime {Date} Time when contact was opted-out.
     * @param firstName {String} Unsubscribed contact first name.
     * @param lastName {String} Unsubscribed contact last name.
     */
    constructor(id, phone, unsubscribeTime, firstName, lastName) { 
        
        UnsubscribedContact.initialize(this, id, phone, unsubscribeTime, firstName, lastName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, phone, unsubscribeTime, firstName, lastName) { 
        obj['id'] = id;
        obj['phone'] = phone;
        obj['unsubscribeTime'] = unsubscribeTime;
        obj['firstName'] = firstName;
        obj['lastName'] = lastName;
    }

    /**
     * Constructs a <code>UnsubscribedContact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UnsubscribedContact} obj Optional instance to populate.
     * @return {module:model/UnsubscribedContact} The populated <code>UnsubscribedContact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UnsubscribedContact();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('unsubscribeTime')) {
                obj['unsubscribeTime'] = ApiClient.convertToType(data['unsubscribeTime'], 'Date');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UnsubscribedContact</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UnsubscribedContact</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UnsubscribedContact.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }

        return true;
    }


}

UnsubscribedContact.RequiredProperties = ["id", "phone", "unsubscribeTime", "firstName", "lastName"];

/**
 * Unsubscribed contact ID.
 * @member {Number} id
 */
UnsubscribedContact.prototype['id'] = undefined;

/**
 * Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).
 * @member {String} phone
 */
UnsubscribedContact.prototype['phone'] = undefined;

/**
 * Time when contact was opted-out.
 * @member {Date} unsubscribeTime
 */
UnsubscribedContact.prototype['unsubscribeTime'] = undefined;

/**
 * Unsubscribed contact first name.
 * @member {String} firstName
 */
UnsubscribedContact.prototype['firstName'] = undefined;

/**
 * Unsubscribed contact last name.
 * @member {String} lastName
 */
UnsubscribedContact.prototype['lastName'] = undefined;






export default UnsubscribedContact;

