/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateInboundMessagesNotificationSettingsRequest model module.
 * @module model/UpdateInboundMessagesNotificationSettingsRequest
 * @version 3.0.43879
 */
class UpdateInboundMessagesNotificationSettingsRequest {
    /**
     * Constructs a new <code>UpdateInboundMessagesNotificationSettingsRequest</code>.
     * @alias module:model/UpdateInboundMessagesNotificationSettingsRequest
     */
    constructor() { 
        
        UpdateInboundMessagesNotificationSettingsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateInboundMessagesNotificationSettingsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateInboundMessagesNotificationSettingsRequest} obj Optional instance to populate.
     * @return {module:model/UpdateInboundMessagesNotificationSettingsRequest} The populated <code>UpdateInboundMessagesNotificationSettingsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateInboundMessagesNotificationSettingsRequest();

            if (data.hasOwnProperty('inboundMessageNotification')) {
                obj['inboundMessageNotification'] = ApiClient.convertToType(data['inboundMessageNotification'], 'Boolean');
            }
            if (data.hasOwnProperty('includeSmsHistory')) {
                obj['includeSmsHistory'] = ApiClient.convertToType(data['includeSmsHistory'], 'Boolean');
            }
            if (data.hasOwnProperty('sendInHtmlFormat')) {
                obj['sendInHtmlFormat'] = ApiClient.convertToType(data['sendInHtmlFormat'], 'Boolean');
            }
            if (data.hasOwnProperty('alertEmail1')) {
                obj['alertEmail1'] = ApiClient.convertToType(data['alertEmail1'], 'String');
            }
            if (data.hasOwnProperty('alertEmail2')) {
                obj['alertEmail2'] = ApiClient.convertToType(data['alertEmail2'], 'String');
            }
            if (data.hasOwnProperty('alertEmail3')) {
                obj['alertEmail3'] = ApiClient.convertToType(data['alertEmail3'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateInboundMessagesNotificationSettingsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateInboundMessagesNotificationSettingsRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['alertEmail1'] && !(typeof data['alertEmail1'] === 'string' || data['alertEmail1'] instanceof String)) {
            throw new Error("Expected the field `alertEmail1` to be a primitive type in the JSON string but got " + data['alertEmail1']);
        }
        // ensure the json data is a string
        if (data['alertEmail2'] && !(typeof data['alertEmail2'] === 'string' || data['alertEmail2'] instanceof String)) {
            throw new Error("Expected the field `alertEmail2` to be a primitive type in the JSON string but got " + data['alertEmail2']);
        }
        // ensure the json data is a string
        if (data['alertEmail3'] && !(typeof data['alertEmail3'] === 'string' || data['alertEmail3'] instanceof String)) {
            throw new Error("Expected the field `alertEmail3` to be a primitive type in the JSON string but got " + data['alertEmail3']);
        }

        return true;
    }


}



/**
 * Should user receive notification about new incoming messages.
 * @member {Boolean} inboundMessageNotification
 */
UpdateInboundMessagesNotificationSettingsRequest.prototype['inboundMessageNotification'] = undefined;

/**
 * Include SMS history into notification Email.
 * @member {Boolean} includeSmsHistory
 */
UpdateInboundMessagesNotificationSettingsRequest.prototype['includeSmsHistory'] = undefined;

/**
 * Send Email notification in HTML format.
 * @member {Boolean} sendInHtmlFormat
 */
UpdateInboundMessagesNotificationSettingsRequest.prototype['sendInHtmlFormat'] = undefined;

/**
 * New message notification email 2.
 * @member {String} alertEmail1
 */
UpdateInboundMessagesNotificationSettingsRequest.prototype['alertEmail1'] = undefined;

/**
 * New message notification email 2.
 * @member {String} alertEmail2
 */
UpdateInboundMessagesNotificationSettingsRequest.prototype['alertEmail2'] = undefined;

/**
 * New message notification email 3.
 * @member {String} alertEmail3
 */
UpdateInboundMessagesNotificationSettingsRequest.prototype['alertEmail3'] = undefined;






export default UpdateInboundMessagesNotificationSettingsRequest;

