/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateChatDesktopNotificationSettingsRequest model module.
 * @module model/UpdateChatDesktopNotificationSettingsRequest
 * @version 3.0.43879
 */
class UpdateChatDesktopNotificationSettingsRequest {
    /**
     * Constructs a new <code>UpdateChatDesktopNotificationSettingsRequest</code>.
     * @alias module:model/UpdateChatDesktopNotificationSettingsRequest
     */
    constructor() { 
        
        UpdateChatDesktopNotificationSettingsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateChatDesktopNotificationSettingsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateChatDesktopNotificationSettingsRequest} obj Optional instance to populate.
     * @return {module:model/UpdateChatDesktopNotificationSettingsRequest} The populated <code>UpdateChatDesktopNotificationSettingsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateChatDesktopNotificationSettingsRequest();

            if (data.hasOwnProperty('playSound')) {
                obj['playSound'] = ApiClient.convertToType(data['playSound'], 'Boolean');
            }
            if (data.hasOwnProperty('showNotifications')) {
                obj['showNotifications'] = ApiClient.convertToType(data['showNotifications'], 'Boolean');
            }
            if (data.hasOwnProperty('showText')) {
                obj['showText'] = ApiClient.convertToType(data['showText'], 'Boolean');
            }
            if (data.hasOwnProperty('soundId')) {
                obj['soundId'] = ApiClient.convertToType(data['soundId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateChatDesktopNotificationSettingsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateChatDesktopNotificationSettingsRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Enable notification sound?
 * @member {Boolean} playSound
 */
UpdateChatDesktopNotificationSettingsRequest.prototype['playSound'] = undefined;

/**
 * Show desktop notifications about new messages.
 * @member {Boolean} showNotifications
 */
UpdateChatDesktopNotificationSettingsRequest.prototype['showNotifications'] = undefined;

/**
 * Incoming message text will be displayed in desktop notifications.
 * @member {Boolean} showText
 */
UpdateChatDesktopNotificationSettingsRequest.prototype['showText'] = undefined;

/**
 * Sound Id of a notification.
 * @member {Number} soundId
 */
UpdateChatDesktopNotificationSettingsRequest.prototype['soundId'] = undefined;






export default UpdateChatDesktopNotificationSettingsRequest;

