/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateCallbackSettingsRequest model module.
 * @module model/UpdateCallbackSettingsRequest
 * @version 3.0.43874
 */
class UpdateCallbackSettingsRequest {
    /**
     * Constructs a new <code>UpdateCallbackSettingsRequest</code>.
     * @alias module:model/UpdateCallbackSettingsRequest
     */
    constructor() { 
        
        UpdateCallbackSettingsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateCallbackSettingsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateCallbackSettingsRequest} obj Optional instance to populate.
     * @return {module:model/UpdateCallbackSettingsRequest} The populated <code>UpdateCallbackSettingsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateCallbackSettingsRequest();

            if (data.hasOwnProperty('outUrl')) {
                obj['outUrl'] = ApiClient.convertToType(data['outUrl'], 'String');
            }
            if (data.hasOwnProperty('inUrl')) {
                obj['inUrl'] = ApiClient.convertToType(data['inUrl'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateCallbackSettingsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateCallbackSettingsRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['outUrl'] && !(typeof data['outUrl'] === 'string' || data['outUrl'] instanceof String)) {
            throw new Error("Expected the field `outUrl` to be a primitive type in the JSON string but got " + data['outUrl']);
        }
        // ensure the json data is a string
        if (data['inUrl'] && !(typeof data['inUrl'] === 'string' || data['inUrl'] instanceof String)) {
            throw new Error("Expected the field `inUrl` to be a primitive type in the JSON string but got " + data['inUrl']);
        }
        // ensure the json data is a string
        if (data['format'] && !(typeof data['format'] === 'string' || data['format'] instanceof String)) {
            throw new Error("Expected the field `format` to be a primitive type in the JSON string but got " + data['format']);
        }

        return true;
    }


}



/**
 * This URL is used to push message delivery status updates to your application.
 * @member {String} outUrl
 */
UpdateCallbackSettingsRequest.prototype['outUrl'] = undefined;

/**
 * This URL is used to push incoming SMS to your application.
 * @member {String} inUrl
 */
UpdateCallbackSettingsRequest.prototype['inUrl'] = undefined;

/**
 * Desired callback data format. m - multipart/form-data, u - application/x-www-form-urlencoded, j - application/json
 * @member {module:model/UpdateCallbackSettingsRequest.FormatEnum} format
 */
UpdateCallbackSettingsRequest.prototype['format'] = undefined;





/**
 * Allowed values for the <code>format</code> property.
 * @enum {String}
 * @readonly
 */
UpdateCallbackSettingsRequest['FormatEnum'] = {

    /**
     * value: "m"
     * @const
     */
    "m": "m",

    /**
     * value: "u"
     * @const
     */
    "u": "u",

    /**
     * value: "j"
     * @const
     */
    "j": "j"
};



export default UpdateCallbackSettingsRequest;

