/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UploadMessageAttachmentResponse model module.
 * @module model/UploadMessageAttachmentResponse
 * @version 3.0.43874
 */
class UploadMessageAttachmentResponse {
    /**
     * Constructs a new <code>UploadMessageAttachmentResponse</code>.
     * @alias module:model/UploadMessageAttachmentResponse
     * @param chars {Number} `href` field characters count. 
     * @param href {String} This is a relative link to your file. To construct a full link, just add “[https://my.textmagic.com/”](https://my.textmagic.com/%E2%80%9D) to the beginning (like this: [https://my.textmagic.com/click/Zwcj9](https://my.textmagic.com/click/Zwcj9)). For most modern devices, you can omit the “https://” part and write just [my.textmagic.com/click/Zwcj9](https://my.textmagic.com/click/Zwcj9), which will save you 8 characters. 
     * @param name {String} File name of the uploaded file. 
     * @param size {Number} Attachment size in bytes.
     * @param resource {String} Internal file name
     */
    constructor(chars, href, name, size, resource) { 
        
        UploadMessageAttachmentResponse.initialize(this, chars, href, name, size, resource);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, chars, href, name, size, resource) { 
        obj['chars'] = chars;
        obj['href'] = href;
        obj['name'] = name;
        obj['size'] = size;
        obj['resource'] = resource;
    }

    /**
     * Constructs a <code>UploadMessageAttachmentResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UploadMessageAttachmentResponse} obj Optional instance to populate.
     * @return {module:model/UploadMessageAttachmentResponse} The populated <code>UploadMessageAttachmentResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UploadMessageAttachmentResponse();

            if (data.hasOwnProperty('chars')) {
                obj['chars'] = ApiClient.convertToType(data['chars'], 'Number');
            }
            if (data.hasOwnProperty('href')) {
                obj['href'] = ApiClient.convertToType(data['href'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('resource')) {
                obj['resource'] = ApiClient.convertToType(data['resource'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UploadMessageAttachmentResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UploadMessageAttachmentResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UploadMessageAttachmentResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['href'] && !(typeof data['href'] === 'string' || data['href'] instanceof String)) {
            throw new Error("Expected the field `href` to be a primitive type in the JSON string but got " + data['href']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['resource'] && !(typeof data['resource'] === 'string' || data['resource'] instanceof String)) {
            throw new Error("Expected the field `resource` to be a primitive type in the JSON string but got " + data['resource']);
        }

        return true;
    }


}

UploadMessageAttachmentResponse.RequiredProperties = ["chars", "href", "name", "size", "resource"];

/**
 * `href` field characters count. 
 * @member {Number} chars
 */
UploadMessageAttachmentResponse.prototype['chars'] = undefined;

/**
 * This is a relative link to your file. To construct a full link, just add “[https://my.textmagic.com/”](https://my.textmagic.com/%E2%80%9D) to the beginning (like this: [https://my.textmagic.com/click/Zwcj9](https://my.textmagic.com/click/Zwcj9)). For most modern devices, you can omit the “https://” part and write just [my.textmagic.com/click/Zwcj9](https://my.textmagic.com/click/Zwcj9), which will save you 8 characters. 
 * @member {String} href
 */
UploadMessageAttachmentResponse.prototype['href'] = undefined;

/**
 * File name of the uploaded file. 
 * @member {String} name
 */
UploadMessageAttachmentResponse.prototype['name'] = undefined;

/**
 * Attachment size in bytes.
 * @member {Number} size
 */
UploadMessageAttachmentResponse.prototype['size'] = undefined;

/**
 * Internal file name
 * @member {String} resource
 */
UploadMessageAttachmentResponse.prototype['resource'] = undefined;






export default UploadMessageAttachmentResponse;

