/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Country from './Country';
import Currency from './Currency';
import Timezone from './Timezone';
import UserImage from './UserImage';

/**
 * The User model module.
 * @module model/User
 * @version 3.0.43874
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     * @param id {Number} User ID.
     * @param username {String} Username.
     * @param firstName {String} Account first name.
     * @param lastName {String} Account last name.
     * @param email {String} User email address.
     * @param status {module:model/User.StatusEnum} Current account status: * **A** for Active; * **T** for Trial. 
     * @param balance {Number} Account balance (in account currency).
     * @param phone {String} User's phone number.
     * @param company {String} Account company name.
     * @param currency {module:model/Currency} 
     * @param country {module:model/Country} 
     * @param timezone {module:model/Timezone} 
     * @param subaccountType {module:model/User.SubaccountTypeEnum} Type of account: * **P** for Parent User; * **A** for Administrator Sub-Account; * **U** for Regular User. 
     * @param emailAccepted {Boolean} Does the account have a confirmed email?
     * @param phoneAccepted {Boolean} Does the account have a confirmed phone number?
     * @param avatar {module:model/UserImage} 
     */
    constructor(id, username, firstName, lastName, email, status, balance, phone, company, currency, country, timezone, subaccountType, emailAccepted, phoneAccepted, avatar) { 
        
        User.initialize(this, id, username, firstName, lastName, email, status, balance, phone, company, currency, country, timezone, subaccountType, emailAccepted, phoneAccepted, avatar);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, username, firstName, lastName, email, status, balance, phone, company, currency, country, timezone, subaccountType, emailAccepted, phoneAccepted, avatar) { 
        obj['id'] = id;
        obj['username'] = username;
        obj['firstName'] = firstName;
        obj['lastName'] = lastName;
        obj['email'] = email;
        obj['status'] = status;
        obj['balance'] = balance;
        obj['phone'] = phone;
        obj['company'] = company;
        obj['currency'] = currency;
        obj['country'] = country;
        obj['timezone'] = timezone;
        obj['subaccountType'] = subaccountType;
        obj['emailAccepted'] = emailAccepted;
        obj['phoneAccepted'] = phoneAccepted;
        obj['avatar'] = avatar;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('displayTimeFormat')) {
                obj['displayTimeFormat'] = ApiClient.convertToType(data['displayTimeFormat'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = Currency.constructFromObject(data['currency']);
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = Country.constructFromObject(data['country']);
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = Timezone.constructFromObject(data['timezone']);
            }
            if (data.hasOwnProperty('subaccountType')) {
                obj['subaccountType'] = ApiClient.convertToType(data['subaccountType'], 'String');
            }
            if (data.hasOwnProperty('emailAccepted')) {
                obj['emailAccepted'] = ApiClient.convertToType(data['emailAccepted'], 'Boolean');
            }
            if (data.hasOwnProperty('phoneAccepted')) {
                obj['phoneAccepted'] = ApiClient.convertToType(data['phoneAccepted'], 'Boolean');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = UserImage.constructFromObject(data['avatar']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>User</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>User</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of User.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['displayTimeFormat'] && !(typeof data['displayTimeFormat'] === 'string' || data['displayTimeFormat'] instanceof String)) {
            throw new Error("Expected the field `displayTimeFormat` to be a primitive type in the JSON string but got " + data['displayTimeFormat']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['company'] && !(typeof data['company'] === 'string' || data['company'] instanceof String)) {
            throw new Error("Expected the field `company` to be a primitive type in the JSON string but got " + data['company']);
        }
        // validate the optional field `currency`
        if (data['currency']) { // data not null
          Currency.validateJSON(data['currency']);
        }
        // validate the optional field `country`
        if (data['country']) { // data not null
          Country.validateJSON(data['country']);
        }
        // validate the optional field `timezone`
        if (data['timezone']) { // data not null
          Timezone.validateJSON(data['timezone']);
        }
        // ensure the json data is a string
        if (data['subaccountType'] && !(typeof data['subaccountType'] === 'string' || data['subaccountType'] instanceof String)) {
            throw new Error("Expected the field `subaccountType` to be a primitive type in the JSON string but got " + data['subaccountType']);
        }
        // validate the optional field `avatar`
        if (data['avatar']) { // data not null
          UserImage.validateJSON(data['avatar']);
        }

        return true;
    }


}

User.RequiredProperties = ["id", "username", "firstName", "lastName", "email", "status", "balance", "phone", "company", "currency", "country", "timezone", "subaccountType", "emailAccepted", "phoneAccepted", "avatar"];

/**
 * User ID.
 * @member {Number} id
 */
User.prototype['id'] = undefined;

/**
 * User's preferred format of time display: * *12h* - AM/PM format; * *24h* - 24-hour clock format. 
 * @member {module:model/User.DisplayTimeFormatEnum} displayTimeFormat
 */
User.prototype['displayTimeFormat'] = undefined;

/**
 * Username.
 * @member {String} username
 */
User.prototype['username'] = undefined;

/**
 * Account first name.
 * @member {String} firstName
 */
User.prototype['firstName'] = undefined;

/**
 * Account last name.
 * @member {String} lastName
 */
User.prototype['lastName'] = undefined;

/**
 * User email address.
 * @member {String} email
 */
User.prototype['email'] = undefined;

/**
 * Current account status: * **A** for Active; * **T** for Trial. 
 * @member {module:model/User.StatusEnum} status
 */
User.prototype['status'] = undefined;

/**
 * Account balance (in account currency).
 * @member {Number} balance
 */
User.prototype['balance'] = undefined;

/**
 * User's phone number.
 * @member {String} phone
 */
User.prototype['phone'] = undefined;

/**
 * Account company name.
 * @member {String} company
 */
User.prototype['company'] = undefined;

/**
 * @member {module:model/Currency} currency
 */
User.prototype['currency'] = undefined;

/**
 * @member {module:model/Country} country
 */
User.prototype['country'] = undefined;

/**
 * @member {module:model/Timezone} timezone
 */
User.prototype['timezone'] = undefined;

/**
 * Type of account: * **P** for Parent User; * **A** for Administrator Sub-Account; * **U** for Regular User. 
 * @member {module:model/User.SubaccountTypeEnum} subaccountType
 */
User.prototype['subaccountType'] = undefined;

/**
 * Does the account have a confirmed email?
 * @member {Boolean} emailAccepted
 */
User.prototype['emailAccepted'] = undefined;

/**
 * Does the account have a confirmed phone number?
 * @member {Boolean} phoneAccepted
 */
User.prototype['phoneAccepted'] = undefined;

/**
 * @member {module:model/UserImage} avatar
 */
User.prototype['avatar'] = undefined;





/**
 * Allowed values for the <code>displayTimeFormat</code> property.
 * @enum {String}
 * @readonly
 */
User['DisplayTimeFormatEnum'] = {

    /**
     * value: "12h"
     * @const
     */
    "12h": "12h",

    /**
     * value: "24h"
     * @const
     */
    "24h": "24h"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
User['StatusEnum'] = {

    /**
     * value: "A"
     * @const
     */
    "A": "A",

    /**
     * value: "T"
     * @const
     */
    "T": "T"
};


/**
 * Allowed values for the <code>subaccountType</code> property.
 * @enum {String}
 * @readonly
 */
User['SubaccountTypeEnum'] = {

    /**
     * value: "P"
     * @const
     */
    "P": "P",

    /**
     * value: "A"
     * @const
     */
    "A": "A",

    /**
     * value: "U"
     * @const
     */
    "U": "U"
};



export default User;

