/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Country from './Country';
import User from './User';

/**
 * The UsersInbound model module.
 * @module model/UsersInbound
 * @version 3.0.43874
 */
class UsersInbound {
    /**
     * Constructs a new <code>UsersInbound</code>.
     * @alias module:model/UsersInbound
     * @param id {Number} Dedicated number ID.
     * @param user {module:model/User} 
     * @param purchasedAt {Date} Time when the dedicated number was purchased.
     * @param expireAt {Date} Dedicated number subscription expiration time.
     * @param status {module:model/UsersInbound.StatusEnum} Number status: *   **U** for Unused. No messages have been sent from (or received to) this number; *   **A** for Active. 
     * @param country {module:model/Country} 
     */
    constructor(id, user, purchasedAt, expireAt, status, country) { 
        
        UsersInbound.initialize(this, id, user, purchasedAt, expireAt, status, country);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, user, purchasedAt, expireAt, status, country) { 
        obj['id'] = id;
        obj['user'] = user;
        obj['purchasedAt'] = purchasedAt;
        obj['expireAt'] = expireAt;
        obj['status'] = status;
        obj['country'] = country;
    }

    /**
     * Constructs a <code>UsersInbound</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersInbound} obj Optional instance to populate.
     * @return {module:model/UsersInbound} The populated <code>UsersInbound</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersInbound();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('displayTimeFormat')) {
                obj['displayTimeFormat'] = ApiClient.convertToType(data['displayTimeFormat'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('purchasedAt')) {
                obj['purchasedAt'] = ApiClient.convertToType(data['purchasedAt'], 'Date');
            }
            if (data.hasOwnProperty('expireAt')) {
                obj['expireAt'] = ApiClient.convertToType(data['expireAt'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = Country.constructFromObject(data['country']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersInbound</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersInbound</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UsersInbound.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['displayTimeFormat'] && !(typeof data['displayTimeFormat'] === 'string' || data['displayTimeFormat'] instanceof String)) {
            throw new Error("Expected the field `displayTimeFormat` to be a primitive type in the JSON string but got " + data['displayTimeFormat']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // validate the optional field `user`
        if (data['user']) { // data not null
          User.validateJSON(data['user']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // validate the optional field `country`
        if (data['country']) { // data not null
          Country.validateJSON(data['country']);
        }

        return true;
    }


}

UsersInbound.RequiredProperties = ["id", "user", "purchasedAt", "expireAt", "status", "country"];

/**
 * Dedicated number ID.
 * @member {Number} id
 */
UsersInbound.prototype['id'] = undefined;

/**
 * Format for representation of time.
 * @member {String} displayTimeFormat
 */
UsersInbound.prototype['displayTimeFormat'] = undefined;

/**
 * Dedicated phone number.
 * @member {String} phone
 */
UsersInbound.prototype['phone'] = undefined;

/**
 * @member {module:model/User} user
 */
UsersInbound.prototype['user'] = undefined;

/**
 * Time when the dedicated number was purchased.
 * @member {Date} purchasedAt
 */
UsersInbound.prototype['purchasedAt'] = undefined;

/**
 * Dedicated number subscription expiration time.
 * @member {Date} expireAt
 */
UsersInbound.prototype['expireAt'] = undefined;

/**
 * Number status: *   **U** for Unused. No messages have been sent from (or received to) this number; *   **A** for Active. 
 * @member {module:model/UsersInbound.StatusEnum} status
 */
UsersInbound.prototype['status'] = undefined;

/**
 * @member {module:model/Country} country
 */
UsersInbound.prototype['country'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
UsersInbound['StatusEnum'] = {

    /**
     * value: "U"
     * @const
     */
    "U": "U",

    /**
     * value: "A"
     * @const
     */
    "A": "A"
};



export default UsersInbound;

