/*
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TextmagicClient);
  }
}(this, function(expect, TextmagicClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Conversation', function() {
      beforeEach(function() {
        instance = new TextmagicClient.Conversation();
      });

      it('should create an instance of Conversation', function() {
        // TODO: update the code to test Conversation
        expect(instance).to.be.a(TextmagicClient.Conversation);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property direction (base name: "direction")', function() {
        // TODO: update the code to test the property direction
        expect(instance).to.have.property('direction');
        // expect(instance.direction).to.be(expectedValueLiteral);
      });

      it('should have the property sender (base name: "sender")', function() {
        // TODO: update the code to test the property sender
        expect(instance).to.have.property('sender');
        // expect(instance.sender).to.be(expectedValueLiteral);
      });

      it('should have the property messageTime (base name: "messageTime")', function() {
        // TODO: update the code to test the property messageTime
        expect(instance).to.have.property('messageTime');
        // expect(instance.messageTime).to.be(expectedValueLiteral);
      });

      it('should have the property text (base name: "text")', function() {
        // TODO: update the code to test the property text
        expect(instance).to.have.property('text');
        // expect(instance.text).to.be(expectedValueLiteral);
      });

      it('should have the property receiver (base name: "receiver")', function() {
        // TODO: update the code to test the property receiver
        expect(instance).to.have.property('receiver');
        // expect(instance.receiver).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property firstName (base name: "firstName")', function() {
        // TODO: update the code to test the property firstName
        expect(instance).to.have.property('firstName');
        // expect(instance.firstName).to.be(expectedValueLiteral);
      });

      it('should have the property lastName (base name: "lastName")', function() {
        // TODO: update the code to test the property lastName
        expect(instance).to.have.property('lastName');
        // expect(instance.lastName).to.be(expectedValueLiteral);
      });

      it('should have the property sessionId (base name: "sessionId")', function() {
        // TODO: update the code to test the property sessionId
        expect(instance).to.have.property('sessionId');
        // expect(instance.sessionId).to.be(expectedValueLiteral);
      });

      it('should have the property initiatorId (base name: "initiatorId")', function() {
        // TODO: update the code to test the property initiatorId
        expect(instance).to.have.property('initiatorId');
        // expect(instance.initiatorId).to.be(expectedValueLiteral);
      });

      it('should have the property messageFileId (base name: "messageFileId")', function() {
        // TODO: update the code to test the property messageFileId
        expect(instance).to.have.property('messageFileId');
        // expect(instance.messageFileId).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property chatType (base name: "chatType")', function() {
        // TODO: update the code to test the property chatType
        expect(instance).to.have.property('chatType');
        // expect(instance.chatType).to.be(expectedValueLiteral);
      });

      it('should have the property chatId (base name: "chatId")', function() {
        // TODO: update the code to test the property chatId
        expect(instance).to.have.property('chatId');
        // expect(instance.chatId).to.be(expectedValueLiteral);
      });

      it('should have the property isEdited (base name: "isEdited")', function() {
        // TODO: update the code to test the property isEdited
        expect(instance).to.have.property('isEdited');
        // expect(instance.isEdited).to.be(expectedValueLiteral);
      });

      it('should have the property errorCode (base name: "errorCode")', function() {
        // TODO: update the code to test the property errorCode
        expect(instance).to.have.property('errorCode');
        // expect(instance.errorCode).to.be(expectedValueLiteral);
      });

      it('should have the property files (base name: "files")', function() {
        // TODO: update the code to test the property files
        expect(instance).to.have.property('files');
        // expect(instance.files).to.be(expectedValueLiteral);
      });

      it('should have the property payload (base name: "payload")', function() {
        // TODO: update the code to test the property payload
        expect(instance).to.have.property('payload');
        // expect(instance.payload).to.be(expectedValueLiteral);
      });

      it('should have the property avatar (base name: "avatar")', function() {
        // TODO: update the code to test the property avatar
        expect(instance).to.have.property('avatar');
        // expect(instance.avatar).to.be(expectedValueLiteral);
      });

    });
  });

}));
