/**
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TextmagicClient);
  }
}(this, function(expect, TextmagicClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetBalanceNotificationOptionsResponse', function() {
    it('should create an instance of GetBalanceNotificationOptionsResponse', function() {
      // uncomment below and update the code to test GetBalanceNotificationOptionsResponse
      //var instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
      //expect(instance).to.be.a(TextmagicClient.GetBalanceNotificationOptionsResponse);
    });

    it('should have the property _1 (base name: "1")', function() {
      // uncomment below and update the code to test the property _1
      //var instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
      //expect(instance).to.be();
    });

    it('should have the property _2 (base name: "2")', function() {
      // uncomment below and update the code to test the property _2
      //var instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
      //expect(instance).to.be();
    });

    it('should have the property _3 (base name: "3")', function() {
      // uncomment below and update the code to test the property _3
      //var instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
      //expect(instance).to.be();
    });

    it('should have the property _5 (base name: "5")', function() {
      // uncomment below and update the code to test the property _5
      //var instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
      //expect(instance).to.be();
    });

    it('should have the property _10 (base name: "10")', function() {
      // uncomment below and update the code to test the property _10
      //var instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
      //expect(instance).to.be();
    });

    it('should have the property _20 (base name: "20")', function() {
      // uncomment below and update the code to test the property _20
      //var instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
      //expect(instance).to.be();
    });

    it('should have the property _30 (base name: "30")', function() {
      // uncomment below and update the code to test the property _30
      //var instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
      //expect(instance).to.be();
    });

    it('should have the property _50 (base name: "50")', function() {
      // uncomment below and update the code to test the property _50
      //var instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
      //expect(instance).to.be();
    });

    it('should have the property _100 (base name: "100")', function() {
      // uncomment below and update the code to test the property _100
      //var instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
      //expect(instance).to.be();
    });

    it('should have the property _500 (base name: "500")', function() {
      // uncomment below and update the code to test the property _500
      //var instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
      //expect(instance).to.be();
    });

    it('should have the property _1000 (base name: "1000")', function() {
      // uncomment below and update the code to test the property _1000
      //var instance = new TextmagicClient.GetBalanceNotificationOptionsResponse();
      //expect(instance).to.be();
    });

  });

}));
