/**
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TextmagicClient);
  }
}(this, function(expect, TextmagicClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TextmagicClient.GetMessageSessionStatResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetMessageSessionStatResponse', function() {
    it('should create an instance of GetMessageSessionStatResponse', function() {
      // uncomment below and update the code to test GetMessageSessionStatResponse
      //var instance = new TextmagicClient.GetMessageSessionStatResponse();
      //expect(instance).to.be.a(TextmagicClient.GetMessageSessionStatResponse);
    });

    it('should have the property failed (base name: "failed")', function() {
      // uncomment below and update the code to test the property failed
      //var instance = new TextmagicClient.GetMessageSessionStatResponse();
      //expect(instance).to.be();
    });

    it('should have the property delivered (base name: "delivered")', function() {
      // uncomment below and update the code to test the property delivered
      //var instance = new TextmagicClient.GetMessageSessionStatResponse();
      //expect(instance).to.be();
    });

    it('should have the property accepted (base name: "accepted")', function() {
      // uncomment below and update the code to test the property accepted
      //var instance = new TextmagicClient.GetMessageSessionStatResponse();
      //expect(instance).to.be();
    });

    it('should have the property rejected (base name: "rejected")', function() {
      // uncomment below and update the code to test the property rejected
      //var instance = new TextmagicClient.GetMessageSessionStatResponse();
      //expect(instance).to.be();
    });

    it('should have the property scheduled (base name: "scheduled")', function() {
      // uncomment below and update the code to test the property scheduled
      //var instance = new TextmagicClient.GetMessageSessionStatResponse();
      //expect(instance).to.be();
    });

    it('should have the property all (base name: "all")', function() {
      // uncomment below and update the code to test the property all
      //var instance = new TextmagicClient.GetMessageSessionStatResponse();
      //expect(instance).to.be();
    });

    it('should have the property sent (base name: "sent")', function() {
      // uncomment below and update the code to test the property sent
      //var instance = new TextmagicClient.GetMessageSessionStatResponse();
      //expect(instance).to.be();
    });

  });

}));
